### ISSUE TITLE
AssemblySnapshotException without details

### ISSUE THREAD

**Issue by sttomm** [cloudfoundry/cf-java-client#1001]
We try to retrieve app and service usage events of some larger CF installations and receive the following exceptions:

```
checkpoint -> org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272)
        |_      Mono.checkpoint ⇢ org.cloudfoundry.reactor.client.v2.applications.ReactorApplicationsV2.list(ReactorApplicationsV2.java:156)
 
        Suppressed: reactor.core.publisher.FluxOnAssembly$AssemblySnapshotException: null
                at reactor.core.publisher.MonoOnAssembly.<init>(MonoOnAssembly.java:62) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at reactor.core.publisher.Mono.checkpoint(Mono.java:1730) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at reactor.core.publisher.Mono.checkpoint(Mono.java:1680) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272) ~[cloudfoundry-client-reactor-3.15.0.RELEASE.jar!/:na]
                at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_212]
                at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.getToken(AbstractUaaTokenProvider.java:108) ~[cloudfoundry-client-reactor-3.15.0.RELEASE.jar!/:na]
                at org.cloudfoundry.reactor.util.AbstractReactorOperations.addAuthorization(AbstractReactorOperations.java:258) ~[cloudfoundry-client-reactor-3.15.0.RELEASE.jar!/:na]
                at reactor.core.publisher.Mono.transform(Mono.java:4093) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at org.cloudfoundry.reactor.util.AbstractReactorOperations.lambda$null$4(AbstractReactorOperations.java:103) ~[cloudfoundry-client-reactor-3.15.0.RELEASE.jar!/:na]
                at reactor.ipc.netty.http.client.HttpClient.lambda$handler$4(HttpClient.java:429) ~[reactor-netty-0.7.9.RELEASE.jar!/:0.7.9.RELEASE]
                at reactor.ipc.netty.http.client.MonoHttpClientResponse$HttpClientHandler.apply(MonoHttpClientResponse.java:121) ~[reactor-netty-0.7.9.RELEASE.jar!/:0.7.9.RELEASE]
                at reactor.ipc.netty.http.client.MonoHttpClientResponse$HttpClientHandler.apply(MonoHttpClientResponse.java:84) ~[reactor-netty-0.7.9.RELEASE.jar!/:0.7.9.RELEASE]
                at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:380) ~[reactor-netty-0.7.9.RELEASE.jar!/:0.7.9.RELEASE]
                at reactor.ipc.netty.http.client.HttpClientOperations.onHandlerStart(HttpClientOperations.java:505) ~[reactor-netty-0.7.9.RELEASE.jar!/:0.7.9.RELEASE]
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.29.Final.jar!/:4.1.29.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-common-4.1.29.Final.jar!/:4.1.29.Final]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.29.Final.jar!/:4.1.29.Final]
                at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
        Suppressed: reactor.core.publisher.FluxOnAssembly$AssemblySnapshotException: null
                at reactor.core.publisher.MonoOnAssembly.<init>(MonoOnAssembly.java:62) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at reactor.core.publisher.Mono.checkpoint(Mono.java:1730) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at reactor.core.publisher.Mono.checkpoint(Mono.java:1680) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at org.cloudfoundry.reactor.client.v2.serviceusageevents.ReactorServiceUsageEvents.list(ReactorServiceUsageEvents.java:55) ~[cloudfoundry-client-reactor-3.15.0.RELEASE.jar!/:na]
                at <our internal class that calls ReactorServiceUsageEvents.list with a page size of 100>
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at reactor.core.publisher.Mono.block(Mono.java:1493) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                ...
        Suppressed: reactor.core.publisher.FluxOnAssembly$AssemblySnapshotException: null
                at reactor.core.publisher.MonoOnAssembly.<init>(MonoOnAssembly.java:62) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at reactor.core.publisher.Mono.checkpoint(Mono.java:1730) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at reactor.core.publisher.Mono.checkpoint(Mono.java:1680) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272) ~[cloudfoundry-client-reactor-3.15.0.RELEASE.jar!/:na]
                at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_212]
                at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.getToken(AbstractUaaTokenProvider.java:108) ~[cloudfoundry-client-reactor-3.15.0.RELEASE.jar!/:na]
                at org.cloudfoundry.reactor.util.AbstractReactorOperations.addAuthorization(AbstractReactorOperations.java:258) ~[cloudfoundry-client-reactor-3.15.0.RELEASE.jar!/:na]
                at reactor.core.publisher.Mono.transform(Mono.java:4093) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at org.cloudfoundry.reactor.util.AbstractReactorOperations.lambda$null$4(AbstractReactorOperations.java:103) ~[cloudfoundry-client-reactor-3.15.0.RELEASE.jar!/:na]
                at reactor.ipc.netty.http.client.HttpClient.lambda$handler$4(HttpClient.java:429) ~[reactor-netty-0.7.9.RELEASE.jar!/:0.7.9.RELEASE]
                at reactor.ipc.netty.http.client.MonoHttpClientResponse$HttpClientHandler.apply(MonoHttpClientResponse.java:121) ~[reactor-netty-0.7.9.RELEASE.jar!/:0.7.9.RELEASE]
                at reactor.ipc.netty.http.client.MonoHttpClientResponse$HttpClientHandler.apply(MonoHttpClientResponse.java:84) ~[reactor-netty-0.7.9.RELEASE.jar!/:0.7.9.RELEASE]
                at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:380) ~[reactor-netty-0.7.9.RELEASE.jar!/:0.7.9.RELEASE]
                at reactor.ipc.netty.http.client.HttpClientOperations.onHandlerStart(HttpClientOperations.java:505) ~[reactor-netty-0.7.9.RELEASE.jar!/:0.7.9.RELEASE]
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.29.Final.jar!/:4.1.29.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-common-4.1.29.Final.jar!/:4.1.29.Final]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.29.Final.jar!/:4.1.29.Final]
                at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
        Suppressed: reactor.core.publisher.FluxOnAssembly$AssemblySnapshotException: null
                at reactor.core.publisher.MonoOnAssembly.<init>(MonoOnAssembly.java:62) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at reactor.core.publisher.Mono.checkpoint(Mono.java:1730) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at reactor.core.publisher.Mono.checkpoint(Mono.java:1680) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
                at org.cloudfoundry.reactor.client.v2.applicationusageevents.ReactorApplicationUsageEvents.list(ReactorApplicationUsageEvents.java:55) ~[cloudfoundry-client-reactor-3.15.0.RELEASE.jar!/:na]
                at <our internal class that calls ReactorApplicationUsageEvents.list with a page size of 100>
```

The exceptions don't contain much valuable information besides "Something went wrong" during the call. Can you provide any hints on what might be going here? Perhaps error handling should also be enhanced in cf-client?

Some more details about what we do is, that we collect the usage events every 30 minutes. We noticed, that the call works the first time, but further calls always run into this issue. The stacktrace is also very large, as the mentioned blocks of the stacktrace appear like a hundred times.

**Comment by dmikusa-pivotal** [comment]
Apologizes that this got overlooked. This occurred in a version of the cf-java-client that's pretty old and unsupported now. If you're still seeing this issue, I would suggest you open a new issue and include your CF version, your cf-java-client version, and [check out our troubleshooting section](https://github.com/cloudfoundry/cf-java-client#troubleshooting) for possible other tips to investigate.
