### ISSUE TITLE
Getting intermittent io.netty.util.IllegalReferenceCountException on invocations of ReactorApplicationsV2#summary

### ISSUE THREAD

**Issue by pacphi** [cloudfoundry/cf-java-client#1005]
I'm using latest version of cf-java-client (3.16.0.RELEASE)...

## Issue

Seeing occurrences of this kind of exception when running [cf-butler](https://github.com/pacphi/cf-butler) against [Pivotal Web Services](https://run.pivotal.io)...

```
2019-10-06T15:02:57,956 ERROR [cloudfoundry-client-nio-5] i.p.c.t.AppDetailTask: AppDetailTask terminated with error
io.netty.util.IllegalReferenceCountException: refCnt: 0
        at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1464)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        |_                    ⇢ at reactor.ipc.netty.ByteBufMono.asString(ByteBufMono.java:78)
        |_                    ⇢ at reactor.ipc.netty.ByteBufMono.asString(ByteBufMono.java:67)
        |_ Mono.switchIfEmpty ⇢ at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$mapToError$10(ErrorPayloadMapper.java:95)
        |_       Mono.flatMap ⇢ at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$mapToError$10(ErrorPayloadMapper.java:96)
        |_       Mono.flatMap ⇢ at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$clientV2$1(ErrorPayloadMapper.java:40)
        |_     Mono.transform ⇢ at org.cloudfoundry.reactor.util.AbstractReactorOperations.lambda$doGet$3(AbstractReactorOperations.java:91)
        |_     Mono.transform ⇢ at org.cloudfoundry.reactor.util.AbstractReactorOperations.doGet(AbstractReactorOperations.java:110)
        |_       Mono.flatMap ⇢ at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$fallback$6(ErrorPayloadMapper.java:61)
        |_     Mono.transform ⇢ at org.cloudfoundry.reactor.util.AbstractReactorOperations.doGet(AbstractReactorOperations.java:111)
        |_   Mono.flatMapMany ⇢ at org.cloudfoundry.reactor.util.JsonCodec.lambda$decode$2(JsonCodec.java:46)
        |_     Mono.transform ⇢ at org.cloudfoundry.reactor.util.AbstractReactorOperations.lambda$deserializedResponse$22(AbstractReactorOperations.java:270)
        |_      Mono.doOnNext ⇢ at org.cloudfoundry.reactor.util.AbstractReactorOperations.lambda$deserializedResponse$22(AbstractReactorOperations.java:271)
        |_     Mono.doOnError ⇢ at org.cloudfoundry.reactor.util.AbstractReactorOperations.lambda$deserializedResponse$22(AbstractReactorOperations.java:272)
        |_     Mono.transform ⇢ at org.cloudfoundry.reactor.util.AbstractReactorOperations.doGet(AbstractReactorOperations.java:92)
        |_                    ⇢ at org.cloudfoundry.reactor.client.v2.AbstractClientV2Operations.get(AbstractClientV2Operations.java:52)
        |_    Mono.checkpoint ⇢ at org.cloudfoundry.reactor.client.v2.applications.ReactorApplicationsV2.summary(ReactorApplicationsV2.java:198)
        |_                    ⇢ at io.pivotal.cfapp.task.AppDetailTask.getSummaryApplicationResponse(AppDetailTask.java:153)
        |_           Mono.zip ⇢ at io.pivotal.cfapp.task.AppDetailTask.lambda$7(AppDetailTask.java:142)
        |_ Mono.onErrorResume ⇢ at io.pivotal.cfapp.task.AppDetailTask.getApplicationDetail(AppDetailTask.java:137)
        |_           Mono.map ⇢ at io.pivotal.cfapp.task.AppDetailTask.getApplicationDetail(AppDetailTask.java:149)
        |_       Flux.flatMap ⇢ at io.pivotal.cfapp.task.AppDetailTask.collect(AppDetailTask.java:85)
        |_       Flux.flatMap ⇢ at io.pivotal.cfapp.task.AppDetailTask.collect(AppDetailTask.java:86)
        |_      Flux.thenMany ⇢ at io.pivotal.cfapp.task.AppDetailTask.collect(AppDetailTask.java:87)
        |_   Flux.collectList ⇢ at io.pivotal.cfapp.task.AppDetailTask.collect(AppDetailTask.java:88)
```

## Potential Workaround

Rather than go down the rabbit-hole, I first thought I'd try to understand [reference counting in Netty](https://netty.io/wiki/reference-counted-objects.html).  

Maybe there's an opportunity to update the way I'm using a scatter-gather call (`Mono.zipErrorDelay`) to aggregate data from multiple calls?

Rather than invoke cf v2 API I can switch to cf V3 API for fetching  application instance information like: buildpack, stack, statistics, state.

**Comment by pacphi** [comment]
Closing this is not an issue any more.  Dependency management updates manifest another more detailed issue re: use of SummaryApplicationRequest.
