### ISSUE TITLE
Issue while fetching the application environment details

### ISSUE THREAD

**Issue by manitheja1** [cloudfoundry/cf-java-client#1055]
We are using this library to fetch application environment details during binding the broker with the application. It works fine for couple of hours or 1 day . After that we are facing issue while fecthing the details. Upon enabling stacktrace, Got the following exception with uaatokenprovider class as shown below. Could you please help us here? Intersesting thing is it works perfectly fine for 12 hrs or one day and then the error comes as follows:

Exception logs:
io.netty.util.IllegalReferenceCountException: refCnt: 0
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1417)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] Assembly trace from producer [reactor.core.publisher.MonoCacheTime] :
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] reactor.core.publisher.Mono.checkpoint(Mono.java:1865)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] Error has been observed at the following site(s):
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] |_ Mono.checkpoint ⇢ at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] |_ Mono.checkpoint ⇢ at org.cloudfoundry.reactor.client.v2.applications.ReactorApplicationsV2.environment(ReactorApplicationsV2.java:132)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] |_____ Mono.checkpoint ⇢ at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] |_________ Mono.checkpoint ⇢ at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] |_____________ Mono.checkpoint ⇢ at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] |_________________ Mono.checkpoint ⇢ at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] |_____________________ Mono.checkpoint ⇢ at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] |_________________________ Mono.checkpoint ⇢ at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] |_____________________________ Mono.checkpoint ⇢ at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] |_________________________________ Mono.checkpoint ⇢ at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] |_____________________________________ Mono.checkpoint ⇢ at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] |_________________________________________ Mono.checkpoint ⇢ at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:272)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] Stack trace:
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1417)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1356)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.buffer.CompositeByteBuf.nioBuffer(CompositeByteBuf.java:1458)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:775)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1222)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1217)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.ipc.netty.ByteBufMono.lambda$asString$1(ByteBufMono.java:78)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.onNext(MonoUsing.java:229)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:112)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:495)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1712)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.onComplete(MonoReduceSeed.java:156)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.ipc.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:380)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:204)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.ipc.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:345)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.ipc.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:338)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.ipc.netty.channel.ChannelOperations.onHandlerTerminate(ChannelOperations.java:404)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.ipc.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:612)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.ipc.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:138)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1429)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at java.lang.Thread.run(Thread.java:748)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] Suppressed: java.lang.Exception: #block terminated with an error
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.Mono.block(Mono.java:1666)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at apm.service.APMInstanceBindingService.createServiceInstanceBinding(APMInstanceBindingService.java:230)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.servicebroker.controller.ServiceInstanceBindingController.createServiceInstanceBinding(ServiceInstanceBindingController.java:56)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-01T11:32:23.173+05:30 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:77)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:679)
2020-07-01T11:32:23.179+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)

**Comment by twoseat** [comment]
Can you tell me what version of the client you're using please.

**Comment by manitheja1** [comment]
i am using 3.15.0.RELEASE

**Comment by twoseat** [comment]
Your version is 18 months out of date and a number of important functional and security updates, including in the area you're seeing problems with, have been introduced in that time. Please update to `3.25.0.RELEASE` and let me know if you still see the problem.

**Comment by manitheja1** [comment]
Sure will let u know!! but this was working fine before not sure why its failing now.

**Comment by manitheja1** [comment]
we have 3.23.0.RELEASE in our internal repository.Can i use this? i don't have 3.25

**Comment by manitheja1** [comment]
3.12.0.RELEASE/		 	
3.13.0.RELEASE/	 	
3.15.0.RELEASE/		 	
3.17.1.RELEASE/		 	
3.18.0.RELEASE/		 	
3.19.0.RELEASE/		 	
3.20.0.RELEASE/		 	
3.21.0.RELEASE/		 	
3.23.0.RELEASE/		 	
3.9.0.RELEASE/

we have above versions in 3.x. please let me know what versions is feasible 3.23 or 3.9 or latest

**Comment by twoseat** [comment]
Tricky - I can't realistically help you with that old of a version, but I know that there have been changes in your problem area in the very latest release. Can you press for the internal repository to be updated?

**Comment by manitheja1** [comment]
Hi 
I think 3.9.0 is latest than 3.25 right? so i can use that i guess? tell me if i am wrong

Thanks,
Manitheja

**Comment by twoseat** [comment]
`3.9.0` is much earlier than `3.25.0` - we increment the second number indefinitely, so you could theoretically see a `3.100.0` eventually!

**Comment by manitheja1** [comment]
repository is updated but that particular version is not there(3.25). might be not addedd due to some cyber issues i guess. iwill try with 3.9 which is latest in 3.x and let you know.

Thanks for the  help

**Comment by manitheja1** [comment]
if itry using 4.x i am facing more issues, thats why. can you check the issue like what exactly is causing if you don't mind? iwill use 3.23 and try again

**Comment by manitheja1** [comment]
This issue comes after a day working fine.

**Comment by twoseat** [comment]
While updating to `4.x` would be a good thing, and it is feature-matched with `3.x`, I don't recommend it right now as it is a significant change to the underlying reactive framework. The move to `3.25.0` will still be a change, but less intrusive.

Without digging into the details of the issue my two starting ideas for troubleshooting would be:
1. The target CF has been updated, and either the java client or your code isn't compatible with some detail of it.
2. There are problems renewing your access or refresh tokens.

The initial solution to both of those is to update to the latest version of the client.

**Comment by manitheja1** [comment]
Hi ,
Thanks for the response!!
i am getting below exception during start when i use 3.23.release:

 [cloudfoundry-client-epoll-4]: [id: 0xbb8725d1, L:/10.255.150.40:51086 ! R:api.apps.eng.na-4a.gaia.jpmchase.net/169.92.3.183:443] An exception has been observed post termination, use DEBUG level to see the full stack: java.lang.NoSuchMethodError: org.springframework.web.util.UriComponentsBuilder.encode()Lorg/springframework/web/util/UriComponentsBuilder;

**Comment by manitheja1** [comment]
Getting following error while executing request to get any app's env data:

INFO [http-nio-8080-exec-4]: EVENT=[RESPONSE] STATUS=[500]
2020-07-02T11:31:12.146+05:30 [APP/PROC/WEB/0] [OUT] INFO [http-nio-8080-exec-4]: EVENT=[WEB] TIME=[248637]
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] WARN [http-nio-8080-exec-6]: Failed to invoke @ExceptionHandler method: public org.springframework.http.ResponseEntity<org.springframework.cloud.servicebroker.model.ErrorMessage> org.springframework.cloud.servicebroker.controller.BaseController.handleException(java.lang.Exception)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] java.lang.NullPointerException: null
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.util.UrlPathHelper.removeSemicolonContentInternal(UrlPathHelper.java:497)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.util.UrlPathHelper.removeSemicolonContent(UrlPathHelper.java:493)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.util.UrlPathHelper.decodeAndCleanUriString(UrlPathHelper.java:426)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.util.UrlPathHelper.getRequestUri(UrlPathHelper.java:315)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.util.UrlPathHelper.getPathWithinApplication(UrlPathHelper.java:232)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.util.UrlPathHelper.getPathWithinServletMapping(UrlPathHelper.java:184)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.util.UrlPathHelper.getLookupPathForRequest(UrlPathHelper.java:161)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.accept.PathExtensionContentNegotiationStrategy.getMediaTypeKey(PathExtensionContentNegotiationStrategy.java:120)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.accept.AbstractMappingContentNegotiationStrategy.resolveMediaTypes(AbstractMappingContentNegotiationStrategy.java:61)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$OptionalPathExtensionContentNegotiationStrategy.resolveMediaTypes(WebMvcAutoConfiguration.java:599)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.accept.ContentNegotiationManager.resolveMediaTypes(ContentNegotiationManager.java:125)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.getAcceptableMediaTypes(AbstractMessageConverterMethodProcessor.java:329)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:183)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:208)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:81)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:113)
2020-07-02T11:31:12.147+05:30 [APP/PROC/WEB/0] [OUT] at

**Comment by manitheja1** [comment]
i am getting same issue when i use 4.6.8 version as well.

**Comment by twoseat** [comment]
I suspect the second error comes from the first one, as it seems you're not able to encode the target uri correctly because of a dependency issue (the `NoSuchMethodError`). I'm not sure why you're getting that though - obviously it 'works on my machine'.

**Comment by dmikusa-pivotal** [comment]
Closing as this has been open w/out comment for a while. Feel free to reopen if you're still having issues with the latest version of cf-java-client. Thanks
