### ISSUE TITLE
UaaException with no message is thrown

### ISSUE THREAD

**Issue by vnb-dev** [cloudfoundry/cf-java-client#1095]
Hi,

We are using cf-java-client version 3.15.0.RELEASE.

We got a reoccurring exception with no message in it and it appeared constantly until we have restarted the process - then it disappeared. The exception itself does not contain any information about what really happened and what caused that to happen and we cannot investigate the issue and try to prevent it in the future.

The exception was: 

`lambda$createServiceInstance$3

SEVERE: Failed to create service instance in CF!
org.cloudfoundry.uaa.UaaException: null: null
        at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$null$7(ErrorPayloadMapper.java:79)
        at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$null$9(ErrorPayloadMapper.java:98)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
        at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:350)
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:113)
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:486)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1476)
        at reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.onComplete(MonoReduceSeed.java:156)
        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
        at reactor.ipc.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:380)
        at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:204)
        at reactor.ipc.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:345)
        at reactor.ipc.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:338)
        at reactor.ipc.netty.channel.ChannelOperations.onHandlerTerminate(ChannelOperations.java:404)
        at reactor.ipc.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:612)
        at reactor.ipc.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:138)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)`

The CF client is instantiated the following way:

> public CloudFoundryClient create() {
>		ConnectionContext connectionContext = DefaultConnectionContext
>				.builder()
>				.apiHost(config.getCFApiEndpoint())
>				.connectionPoolSize(CF_CONNECTION_POOL_SIZE)
>				.build();
>		TokenProvider tokenProvider = PasswordGrantTokenProvider
>				.builder()
>				.password(config.getTechnicalUserPassword())
>				.username(config.getTechnicalUserUsername())
>				.build();
>		CloudFoundryClient cloudFoundryClient = ReactorCloudFoundryClient
>				.builder()
>				.connectionContext(connectionContext)
>				.tokenProvider(tokenProvider)
>				.build();
>		return cloudFoundryClient;
>}

Could you please help us find out what could have happened and advise us on how to prevent such issues in the future?

**Comment by mheath** [comment]
Have you tried upgrading to `3.29.0.RELEASE`? This may be a bug that has already been fixed.

**Comment by sg1702** [comment]
Hello, we use 4.6.0.RELEASE version of cf-java-client and we are seeing the same issue with this version as well.

**Comment by sg1702** [comment]
hi @mheath , any update on my last query? Thanks!

**Comment by mheath** [comment]
I have only been on CFJC a short time so I don't know if there is a specific fix for this issue. I do know that there have been a variety of issues fixed around Reactor itself and how CFJC uses Reactor that may fix this issue. Sorry, I know that's not the answer you were looking for.

That being said, relying on an old version of CFJC is risky as it may prevent you from applying security fixes. This is probably something that you already know though and I fully understand that managing dependencies can be difficult.

**Comment by sg1702** [comment]
Hi @mheath, thank you for checking. Can you please forward this issue to someone who might be able to pin-point us to the exact fix/commit which was done in order to resolve the issue in latest version of the library.

Yes, I understand the security concern and we always try to update our cf java client library version regularly. But updating to latest cf java library version would take some time (as its a lengthy process internally) and the issue is currently happening on live systems (customer scenarios are impacted). Hence, we are trying to find the actual fix which we can then down-port to the current version that we are using in our product.

**Comment by mheath** [comment]
Unfortunately, anyone who might know the exact commit is no longer with VMware.

**Comment by dmikusa-pivotal** [comment]
@sg1702 Apologizes, but +1 to what @mheath said. I don't know which commit resolved this either.

IMHO, your best bet is to upgrade and confirm that the issue has been fixed. Then you can work back from the fixed version through the release notes to try an locate the change. The release notes for every release contain a link to the "commit log", which shows you everything changed between the releases.

I'm going to close this issue. If you have any follow-up questions, feel free to reopen it.
