### ISSUE TITLE
Java heap exhaustion using CloudControllerClientFactory.newCloudController

### ISSUE THREAD

**Issue by kevin-ortega** [cloudfoundry/cf-java-client#1125]
When our java app invokes the following API we get an OutOfMemoryError (stack pasted below):

CloudControllerClientFactorynewCloudController(URL cloudControllerUrl, CloudCredentials cloudCredentials, String orgName, String spaceName)

Our logging shows url, creds, orgName and spacename do have values.

```
java.lang.OutOfMemoryError: Java heap space
	at java.lang.StringBuilder.ensureCapacityImpl(StringBuilder.java:366)
	at java.lang.StringBuilder.append(StringBuilder.java:118)
	at org.springframework.util.StreamUtils.copyToString(StreamUtils.java:85)
	at org.springframework.http.converter.StringHttpMessageConverter.readInternal(StringHttpMessageConverter.java:86)
	at org.springframework.http.converter.StringHttpMessageConverter.readInternal(StringHttpMessageConverter.java:41)
	at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:193)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:104)
	at org.cloudfoundry.client.lib.rest.LoggingRestTemplate$1.extractData(LoggingRestTemplate.java:61)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:655)
	at org.cloudfoundry.client.lib.rest.LoggingRestTemplate.doExecute(LoggingRestTemplate.java:54)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:287)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.addPageOfResources(CloudControllerClientImpl.java:1229)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getAllResources(CloudControllerClientImpl.java:1222)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getSpaces(CloudControllerClientImpl.java:647)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.validateSpaceAndOrg(CloudControllerClientImpl.java:202)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.<init>(CloudControllerClientImpl.java:178)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientFactory.newCloudController(CloudControllerClientFactory.java:78)
	at com.ibm.ws.icap.runtime.tests.utils.CFv2TestCase.initTestClass(CFv2TestCase.java:325)
	at com.ibm.ws.icap.runtime.tests.utils.SVTTestCase.setUpBeforeClass(SVTTestCase.java:83)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:195)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:108)
```
We have upgraded to the latest cf java client (5.6.0) but the error still occurs. 

Invoking the API runs for about 15 mins and eventually the OutOfMemoryError occurs.   Looking at the heapdump, I can see that the CF java client creates a collection containing almost 50,000 entires and thus consumes the JVMs heap leading to the OutOfMemoryError.  The JVM initially was set for a 1G heap and the CF java client collection grew to about 23,000 entries before the heap is consumed.   I increased the heap to 4G but that just allowed the collection to grow more.

The ID was recently elevated to have admin privileges which I assume is the reason we started seeing this error.   But, because we specify an org and space I didn't expect the API to be affected by the ID's elevated privileges.

**Comment by dmikusa-pivotal** [comment]
@kevin-ortega do you have a stack trace from the app after you upgraded to 5.6.0? That version shouldn't be using RestTemplate, so it's odd to see that in the stacktrace.

Similarly, could you share some screenshots from a heap dump tool to show what's holding references to the list that is growing? I just want to make sure we can pinpoint exactly what is causing the memory growth. I have some ideas, but I just want to make sure.

Thanks

**Comment by kevin-ortega** [comment]
@dmikusa-pivotal Thanks for the quick response.   It looks like it is an arraylist of hashmaps:
![image](https://user-images.githubusercontent.com/29545669/141836491-e116ed35-2822-474d-be53-6f260ff875b2.png)

I'm trying a different tool to see if I can find what's holding the references.   

Anyway, I reran the test but the stack trace is the same, still shows the RestTemplate so clearly It's not running with 5.6.0.   Do you know if I actually was running with 5.6.0 I wouldn't have this issue?

**Comment by dmikusa-pivotal** [comment]
>Anyway, I reran the test but the stack trace is the same, still shows the RestTemplate so clearly It's not running with 5.6.0. Do you know if I actually was running with 5.6.0 I wouldn't have this issue?

Quite a while back, everything was switched off of RestTemplate which is a blocking API to using Project Reactor and Reactor Netty, which is a reactive/async API. So if you had upgraded to 5.6.0 or even 4.x, you wouldn't see RestTemplate anymore. The stack trace also [matches the package names from the older version too](https://github.com/cloudfoundry/cf-java-client/tree/1.x/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib), so it's very likely you're still on the 1.x branch.

I can't say 100% that upgrading would make this issue go away. A *lot* has changed between the 1.x and current branches. From the stack trace on 1.x, you can see that it's loading all of the spaces accessible into memory, which is the problem (you just have a lot of spaces).

In the new versions, we have a separation of code between the client, which mirrors the API, and an "operations" library which composes multiple client operations into more functional blocks. The perfect example of an "operation" is `cf push`. It's actually composed of many client operations.

I can say for sure that the current client isn't going to load up the spaces when you authenticate. It's not designed to work that way. It is only going to do exactly what you tell it. If you say "fetch the spaces", it'll get them but that's it. 

It is possible that the operations library might attempt to do something similar. Not upon login, but because it composes multiple client calls together, there may be an operation that when run would trigger loading spaces, which might cause issues given the number of spaces you have.  That said, there's a good possibility that even with all the spaces the operation would be OK because it's a reactive API that will generally do things in a lazy manner (i.e. only load spaces when they are needed). This tends to keep less information in memory.

If you do see something similar happen with the 4.x or 5.x library, definitely let me know. We can take a closer look. The library that is confirmed to have the issue from the stack trace is very old though and not something that we can presently patch.

**Comment by kevin-ortega** [comment]
@dmikusa-pivotal This clearly is a problem for us because we have such an old java client.  We will migrate to a newer version.  Thanks for looking in to this.
