### ISSUE TITLE
CF Client throws NPE when using OAuthToken without refresh and no expiration

### ISSUE THREAD

**Issue by kdvolder** [cloudfoundry/cf-java-client#214]
Version: 1.0.3

If you use a OAuthToken object like this:

         new DefaultOAuth2AccessToken("...")

You get a token that has no expiration and no refresh token. The way I read the docs this should be ok, you just don't get to refresh that token.

When I put this token in the CF client the client tries to refresh the token when I try connect logregator listener. It sees time until expiration as '0' and thinks its time to refresh. But since there's no refresh token it throws an NPE.

java.lang.NullPointerException
	at org.springframework.security.oauth2.client.token.grant.password.ResourceOwnerPasswordAccessTokenProvider.refreshAccessToken(ResourceOwnerPasswordAccessTokenProvider.java:39)
	at org.cloudfoundry.client.lib.oauth2.OauthClient.refreshToken(OauthClient.java:124)
	at org.cloudfoundry.client.lib.oauth2.OauthClient.getToken(OauthClient.java:88)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getUserInfo(CloudControllerClientImpl.java:1722)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getInfo(CloudControllerClientImpl.java:534)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.streamLoggregatorLogs(CloudControllerClientImpl.java:1631)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.streamLogs(CloudControllerClientImpl.java:233)
	at org.cloudfoundry.client.lib.CloudFoundryClient.streamLogs(CloudFoundryClient.java:336)
	at org.eclipse.flux.cloudfoundry.deployment.service.CloudFoundryClientDelegate$DeployedApplicationLogListener.<init>(CloudFoundryClientDelegate.java:348)
	at org.eclipse.flux.cloudfoundry.deployment.service.CloudFoundryClientDelegate.addLogListener(CloudFoundryClientDelegate.java:186)
	at org.eclipse.flux.cloudfoundry.deployment.service.CloudFoundryClientDelegate$4.doRun(CloudFoundryClientDelegate.java:157)
	at org.eclipse.flux.cloudfoundry.deployment.service.CloudFoundryClientDelegate$4.doRun(CloudFoundryClientDelegate.java:1)
	at org.eclipse.flux.cloudfoundry.deployment.service.CloudFoundryClientDelegate$ApplicationOperation.run(CloudFoundryClientDelegate.java:426)
	at org.eclipse.flux.cloudfoundry.deployment.service.CloudFoundryClientDelegate.upload(CloudFoundryClientDelegate.java:166)
	at org.eclipse.flux.cloudfoundry.deployment.service.CloudFoundryClientDelegate$1.doRun(CloudFoundryClientDelegate.java:104)
	at org.eclipse.flux.cloudfoundry.deployment.service.CloudFoundryClientDelegate$1.doRun(CloudFoundryClientDelegate.java:1)
	at org.eclipse.flux.cloudfoundry.deployment.service.CloudFoundryClientDelegate$ApplicationOperation.run(CloudFoundryClientDelegate.java:426)
	at org.eclipse.flux.cloudfoundry.deployment.service.CloudFoundryClientDelegate.push(CloudFoundryClientDelegate.java:109)
	at org.eclipse.flux.cloudfoundry.deployment.service.CfDeploymentService$2$1$1.downloadComplete(CfDeploymentService.java:152)
	at org.eclipse.flux.cloudfoundry.deployment.service.DownloadProject.getResourceResponse(DownloadProject.java:190)
	at org.eclipse.flux.cloudfoundry.deployment.service.DownloadProject$2.handle(DownloadProject.java:68)
	at org.eclipse.flux.client.impl.SocketIOMessageConnector$4.run(SocketIOMessageConnector.java:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by xtreme-jamil-shamy** [comment]
What about if we are using the OAuth 2.0 Implicit grant type ? We will not get back any refresh token with this specific grant type. Will the cf-java-client support sending only the "access token" in the case of implicit grant type ? 

Please note that the UAA server does support the implicit grant type.

**Comment by scottfrederick** [comment]
Fixed via #259
