### ISSUE TITLE
java.lang.Integer cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by joek** [cloudfoundry/cf-java-client#253]
If there is a numeric ENV variable set to an app in your space you will get an ```java.lang.Integer cannot be cast to java.lang.String```exception while deploying. The reason is, the JSON Parser is creating an integer value of numeric parameters without quotes. 

You will find the broken Method here: https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/domain/CloudApplication.java#L210-L216

Here is the related stackstrace from gradle deploy:
````
:cfDeploy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cfDeploy'.
> java.lang.Integer cannot be cast to java.lang.String

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':cfDeploy'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:296)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:86)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:148)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:105)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:85)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:81)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.cloudfoundry.client.lib.domain.CloudApplication.setEnv(CloudApplication.java:213)
	at org.cloudfoundry.client.lib.util.CloudEntityResourceMapper.mapApplicationResource(CloudEntityResourceMapper.java:177)
	at org.cloudfoundry.client.lib.util.CloudEntityResourceMapper.mapResource(CloudEntityResourceMapper.java:73)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.mapCloudApplication(CloudControllerClientImpl.java:958)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getApplications(CloudControllerClientImpl.java:926)
	at org.cloudfoundry.client.lib.CloudFoundryClient.getApplications(CloudFoundryClient.java:218)
	at org.cloudfoundry.gradle.tasks.DeployCloudFoundryTask$_deploy_closure1.doCall(DeployCloudFoundryTask.groovy:39)
	at org.cloudfoundry.gradle.tasks.AbstractCloudFoundryTask.withCloudFoundryClient(AbstractCloudFoundryTask.groovy:64)
	at org.cloudfoundry.gradle.tasks.DeployCloudFoundryTask.deploy(DeployCloudFoundryTask.groovy:35)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:570)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:553)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 47 more


BUILD FAILED

Total time: 9.409 secs
```

**Comment by scottfrederick** [comment]
@joek The question is, how did an `Integer` get into the JSON in the first place? The `cf` CLI converts env var values to Strings in the app metadata, and the Java client only [accepts String values](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/CloudFoundryClient.java#L341-L347). 

At any rate, fixed via https://github.com/cloudfoundry/cf-java-client/commit/80ede53db362c3eb3d54d3c246f65e445189e50a

**Comment by joek** [comment]
@scottfrederick That is a good question. Maybe it is an bug in the cloudcontroller. The point is, if you put an unquoted numeric env value in your manifest it will end up in the json structure unquoted too. 

There was an similar issue in the CF CLI, they just figured out earlier ;-) https://github.com/cloudfoundry/cli/issues/288

**Comment by stocksnut** [comment]
I am getting this error, when calling the cloud foundry plug-in from Jenkins.  My version of the plug-in is 1.5

**Comment by scottfrederick** [comment]
@stocksnut It looks like version 1.5 of the Jenkins plugin uses version 1.1.3 of the CF Java Client, which should have this fix in it. However it appears that the plugin uses a [customized version of CF Java client](https://github.com/jenkinsci/cloudfoundry/blob/master/pom.xml#L35-L40), so we have no way of knowing what's in there. 

You'll need to contact the maintainers of the [Jenkins plugin](https://github.com/jenkinsci/cloudfoundry) and see if they can provide you with support or a fix.
