### ISSUE TITLE
Gradle plugin NPE listing services

### ISSUE THREAD

**Issue by StephenDillon** [cloudfoundry/cf-java-client#261]
Running cmd > gradle cfServices --info --stacktrace

Outputs
Caused by: java.lang.NullPointerException: Cannot invoke method leftShift() on null object
        at org.cloudfoundry.gradle.tasks.ServicesCloudFoundryTask$_mapServicesToApps_closure3_closure5.doCall(ServicesCloudFoundryTask.groovy:61)
        at org.cloudfoundry.gradle.tasks.ServicesCloudFoundryTask$_mapServicesToApps_closure3.doCall(ServicesCloudFoundryTask.groovy:61)
        at org.cloudfoundry.gradle.tasks.ServicesCloudFoundryTask.mapServicesToApps(ServicesCloudFoundryTask.groovy:60)
        at org.cloudfoundry.gradle.tasks.ServicesCloudFoundryTask$_showServices_closure1.doCall(ServicesCloudFoundryTask.groovy:40)
        at org.cloudfoundry.gradle.tasks.AbstractCloudFoundryTask.withCloudFoundryClient(AbstractCloudFoundryTask.groovy:64)
        at org.cloudfoundry.gradle.tasks.ServicesCloudFoundryTask.showServices(ServicesCloudFoundryTask.groovy:34)

Running gradle 2.1, cf-gradle-plugin 1.1.1, windows 7.

I will try adding some debug information into the plugin and see exactly on what service/app it is failing. Let me know any additional info you might want.

Thanks,
Stephen

**Comment by scottfrederick** [comment]
@StephenDillon It would be useful it you could run `cf CF_TRACE=true services` in the same space and org as you are running the Gradle in, and share the JSON that is displayed, so we see the data that the Gradle plugin is trying to parse.

**Comment by StephenDillon** [comment]
I will try that should it happen again, but it looks like the recent
upgrade of our mysql tile has fixed/hidden the issue.

The issue came up after cfPush was trying to create a mysql service that
already exist and was bound to our app (probably because the services
couldn't be mapped)
It has occurred a few times, i will keep an eye on it and get more
information next time i can trigger it, or if the recent tile upgrade has
resolved it.

**Comment by StephenDillon** [comment]
Updating the MySql broker seems to have fixed the issue, I have seen no occurrences since.

**Comment by scottfrederick** [comment]
Thanks @StephenDillon, let's close this issue then. You can re-open if it happens again and you can provide more details.
