### ISSUE TITLE
NPE when using gradle plugin on PWS Diego

### ISSUE THREAD

**Issue by bclozel** [cloudfoundry/cf-java-client#285]
When [targeting Diego as the deployment platform on PWS](https://github.com/cloudfoundry-incubator/diego-design-notes/blob/master/migrating-to-diego.md), the `gradle deploy` command is failing with a `NullPointerException` thrown by the client lib when parsing a date:

```groovy
Caused by: java.lang.NullPointerException
	at org.cloudfoundry.client.lib.domain.InstanceStats.parseDate(InstanceStats.java:104)
	at org.cloudfoundry.client.lib.domain.InstanceStats.access$000(InstanceStats.java:28)
	at org.cloudfoundry.client.lib.domain.InstanceStats$Usage.<init>(InstanceStats.java:38)
	at org.cloudfoundry.client.lib.domain.InstanceStats.<init>(InstanceStats.java:86)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.doGetApplicationStats(CloudControllerClientImpl.java:1120)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getRunningInstances(CloudControllerClientImpl.java:1097)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.mapCloudApplication(CloudControllerClientImpl.java:1085)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getApplications(CloudControllerClientImpl.java:1042)
	at org.cloudfoundry.client.lib.CloudFoundryClient.getApplications(CloudFoundryClient.java:221)
	at org.cloudfoundry.gradle.tasks.DeployCloudFoundryTask$_deploy_closure1.doCall(DeployCloudFoundryTask.groovy:39)
	at org.cloudfoundry.gradle.tasks.AbstractCloudFoundryTask.withCloudFoundryClient(AbstractCloudFoundryTask.groovy:64)
	at org.cloudfoundry.gradle.tasks.DeployCloudFoundryTask.deploy(DeployCloudFoundryTask.groovy:35)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 56 more
```

Parts of the API have been probably modified - let me know if/how I can provide more information on this.

**Comment by cgfrost** [comment]
Fixed. A missing value in the Application state usage date data returned from the CC API will no longer cause an NPE.
