### ISSUE TITLE
NPE getServiceInstance()

### ISSUE THREAD

**Issue by turbospaces** [cloudfoundry/cf-java-client#316]
(cloudfoundry-client-lib) =(1.1.3)
Method CloudServiceInstance getServiceInstance(String serviceName) throws NPE for user-provided-services

line 264 in CloudEntityResourceMapper has to check if service_plan exists, it seems that for user-provided service it doesn't	
Map<String, Object> servicePlanResource = getEmbeddedResource(resource, "service_plan");

```java
SEVERE: 
java.lang.NullPointerException
	at org.cloudfoundry.client.lib.util.CloudEntityResourceMapper.getMeta(CloudEntityResourceMapper.java:384)
	at org.cloudfoundry.client.lib.util.CloudEntityResourceMapper.mapServicePlanResource(CloudEntityResourceMapper.java:321)
	at org.cloudfoundry.client.lib.util.CloudEntityResourceMapper.mapServiceInstanceResource(CloudEntityResourceMapper.java:265)
	at org.cloudfoundry.client.lib.util.CloudEntityResourceMapper.mapResource(CloudEntityResourceMapper.java:90)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getServiceInstance(CloudControllerClientImpl.java:900)
	at org.cloudfoundry.client.lib.CloudFoundryClient.getServiceInstance(CloudFoundryClient.java:459)
```

**Comment by glyn** [comment]
Fixed by https://github.com/cloudfoundry/cf-java-client/commit/637cd4a62b74ee2685a8dd240e6846a6d89b6c42
