### ISSUE TITLE
loggregator recent logs

### ISSUE THREAD

**Issue by antechrestos** [cloudfoundry/cf-java-client#359]
Hi,

we (@arnaudruffin and I)  are attempting to use the __loggregator__ from the new client library to get recent logs. We see that it does an http ```GET``` request on ```https:/<loggregator url>/recent?app=<id>``` but no log (and no error either) are got (even we know there are some).

```java
        final AtomicInteger count = new AtomicInteger();
        TestSubscriber<LoggregatorMessage> subscriber = new TestSubscriber<>();
        subscriber.assertThat(response -> {
            assertThat(response, is(notNullValue()));
            assertThat(response.getMessage(), is(notNullValue()));
            log.debug("get_last_logs - log {}", response.getMessage());
            count.incrementAndGet();
        });

        Publisher<LoggregatorMessage> publisher = loggregatorClient.recent(RecentLogsRequest.builder().id
                (logApplicationId).build());
        publisher.subscribe(subscriber);
        subscriber.verify(10, TimeUnit.SECONDS);
        log.debug("get_last_logs - {} got", count);
```

We tried to do a http request using our browser and setting the Authorization header to **Bearer \<access token\>** with an access token got from an other part. Doing so a basic auth credential windows asking for username/password is prompt. I tried to enter my cloudfoundry login/password but it kept on rejecting me...

**Comment by antechrestos** [comment]
I guess I did something wrong with the browser cause doing the http request with a python call returned some data... With encoding issue from client side, ture, yet some data still...

**Comment by nebhale** [comment]
We don't currently have any integration tests around this, so I think it's safe to say that it's broken.  I'll take a quick look, but I don't think we'll spend a huge amount of energy fixing it until we replace the network stack, post M1.

**Comment by antechrestos** [comment]
@nebhale I digged a lot. So far:
- Multipart reading :+1: 
- Mocked request :+1: 
- Real requests :-1:  : Adding some logs in the ```org.cloudfoundry.client.spring.util.Multipart``` class lead me to an Exception raised in the ```apply``` function of the ```Function``` anonym subclass passed as second argument to the ```Stream``` creation.
```
java.io.IOException: stream is closed
	at sun.net.www.http.ChunkedInputStream.ensureOpen(ChunkedInputStream.java:174) ~[na:1.7.0_60]
	at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:673) ~[na:1.7.0_60]
	at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[na:1.7.0_60]
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3053) ~[na:1.7.0_60]
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3047) ~[na:1.7.0_60]
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3035) ~[na:1.7.0_60]
	at java.io.FilterInputStream.read(FilterInputStream.java:83) ~[na:1.7.0_60]
	at java.io.PushbackInputStream.read(PushbackInputStream.java:139) ~[na:1.7.0_60]
	at org.cloudfoundry.client.spring.util.Multipart.readLine(Multipart.java:147) ~[classes/:na]
	at org.cloudfoundry.client.spring.util.Multipart.primeStream(Multipart.java:132) ~[classes/:na]
	at org.cloudfoundry.client.spring.util.Multipart.access$200(Multipart.java:33) ~[classes/:na]
	at org.cloudfoundry.client.spring.util.Multipart$2.apply(Multipart.java:69) [classes/:na]
	at org.cloudfoundry.client.spring.util.Multipart$2.apply(Multipart.java:63) [classes/:na]
	at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:72) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.rx.StreamSource$Identity.subscribe(StreamSource.java:99) [reactor-stream-2.5.0.BUILD-20160129.092531-201.jar:na]
	at reactor.rx.StreamMap.subscribe(StreamMap.java:70) [reactor-stream-2.5.0.BUILD-20160129.092531-201.jar:na]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:319) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:85) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.rx.StreamBlock$StreamBlockSubscriber.onNext(StreamBlock.java:124) [reactor-stream-2.5.0.BUILD-20160129.092531-201.jar:na]
	at reactor.core.publisher.ProcessorGroup$DispatchOn.route(ProcessorGroup.java:1316) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.core.publisher.ProcessorGroup$PublishOn.doNext(ProcessorGroup.java:1402) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.core.publisher.ProcessorGroup$DispatchOn.onNext(ProcessorGroup.java:1056) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.core.subscriber.SignalEmitter.emit(SignalEmitter.java:179) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.core.subscriber.SignalEmitter.onNext(SignalEmitter.java:425) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at org.cloudfoundry.client.spring.util.AbstractSpringOperations$2$1.accept(AbstractSpringOperations.java:101) [classes/:na]
	at org.cloudfoundry.client.spring.util.AbstractSpringOperations$2$1.accept(AbstractSpringOperations.java:94) [classes/:na]
	at reactor.core.publisher.FluxYieldingEmitter$YieldingSignalEmitter.request(FluxYieldingEmitter.java:76) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.core.publisher.ProcessorGroup$DispatchOn.doRequest(ProcessorGroup.java:1152) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.core.publisher.ProcessorGroup$PublishOn.run(ProcessorGroup.java:1417) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.core.publisher.ProcessorGroup$PublishOn.request(ProcessorGroup.java:1442) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.rx.StreamBlock$StreamBlockSubscriber.onSubscribe(StreamBlock.java:100) [reactor-stream-2.5.0.BUILD-20160129.092531-201.jar:na]
	at reactor.core.publisher.ProcessorGroup$PublishOn$1.run(ProcessorGroup.java:1390) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.core.publisher.ProcessorGroup$TaskSubscriber.onNext(ProcessorGroup.java:1551) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.core.publisher.ProcessorGroup$TaskSubscriber.onNext(ProcessorGroup.java:1526) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:844) [reactor-core-2.5.0.BUILD-20160129.090711-223.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_60]
```
Maybe transfert-chunked encoding is not well supported?

**Comment by antechrestos** [comment]
@nebhale @arnaudruffin @gberche-orange : See #378
