### ISSUE TITLE
Compatibility with Helion

### ISSUE THREAD

**Issue by robertgmoss** [cloudfoundry/cf-java-client#446]
Hi Folks,

I'm trying to write an app that targets https://api.helionit.io/v2/info, but I'm getting an [SSLException](https://gist.github.com/robertgmoss/012924a4d0f7680b73f3afe9f2b0b255).  I notice that helion is using api version 2.23.0 but this java client is expecting 2.52.0 - Is there a way of targeting an older version of the api? Or can you think of any other reason why it might not be connecting?  I'm connecting with:

    @Bean
    public CloudFoundryClient cloudFoundryClient() {
        return SpringCloudFoundryClient.builder()
                .host(properties.getUrl())
                .username(properties.getUsername())
                .password(properties.getPassword())
                .skipSslValidation(true)
                .build();

**Comment by robertgmoss** [comment]
The issue appears to be happening during `AccessTokenUriBuilder#build()` and appears to be throwing from `RestTemplate#doExecute` when `execute()` is called on the `request`

**Comment by robertgmoss** [comment]
As a test I injected a `RestTemplate` and ran `restTemplate.getForObject(new URI("http://api.helionit.io/v2/info"), Map.class);` on it (note the http not https), and it throws `org.springframework.web.client.HttpClientErrorException: 403 Forbidden` too - not sure why as no authentication is required to access that endpoint (checked with chrome and postman, both access it fine)

**Comment by nebhale** [comment]
@robertgmoss In general, we're the client's goal is to support the latest version of the CF API.  The implementation is incomplete, but the parts that are there are aiming to support 2.52.0 (if they aren't it's a bug).  Looking back through the history of CF's [release history](https://github.com/cloudfoundry/cf-release/releases) it appears that API version 2.23.0 was released as part of [CF 203](https://github.com/cloudfoundry/cf-release/releases/tag/v203) on March 12, 2015.  We will not be doing any work to support a year old version of CF, however I am surprised to see an SSL exception coming out of the client.  That should be handled by the JVM's SSL support and doesn't really have anything to do with our implementation.  If you want to post in the full stack trace of the failure, I'll take a look and see if there's anything obvious that you can fix.

**Comment by robertgmoss** [comment]
@nebhale I've made a bit of progress with the following code in `ConnectionContextFactory`:

    private static RestOperations getRestOperations(HostnameVerifier hostnameVerifier, SSLContext sslContext) {
        RestTemplate restTemplate = new RestTemplate();
        ClientHttpRequestFactory requestFactory = new HttpComponentsClientHttpRequestFactory(getHttpClient(hostnameVerifier, sslContext));
        restTemplate.setRequestFactory(requestFactory);
        return restTemplate;
    }

    private static HttpClient getHttpClient(HostnameVerifier hostnameVerifier, SSLContext sslContext){
        ConnectionSocketFactory plainsf = PlainConnectionSocketFactory.getSocketFactory();
        LayeredConnectionSocketFactory sslsf = new SSLConnectionSocketFactory(sslContext, hostnameVerifier);
        Registry<ConnectionSocketFactory> r = RegistryBuilder.<ConnectionSocketFactory>create()
            .register("http", plainsf)
            .register("https", sslsf)
            .build();
        HttpClientConnectionManager cm = new PoolingHttpClientConnectionManager(r);
        return HttpClients.custom().setConnectionManager(cm).build();
    }

Which allows the inital call to "http://api.helionit.io/v2/info" to work, but then subsequent usage fails:

```
error="access_denied", error_description="Error requesting access token."
	at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:145)
	at org.springframework.security.oauth2.client.token.grant.password.ResourceOwnerPasswordAccessTokenProvider.obtainAccessToken(ResourceOwnerPasswordAccessTokenProvider.java:47)
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221)
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173)
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.createRequest(OAuth2RestTemplate.java:105)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:592)
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:280)
	at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$get$3(AbstractSpringOperations.java:85)
	at org.cloudfoundry.spring.util.AbstractSpringOperations$$Lambda$18/1725151361.apply(Unknown Source)
	at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$null$1(AbstractSpringOperations.java:66)
	at org.cloudfoundry.spring.util.AbstractSpringOperations$$Lambda$23/905993783.accept(Unknown Source)
	at reactor.core.publisher.FluxYieldingEmitter$YieldingSignalEmitter.request(FluxYieldingEmitter.java:72)
	at reactor.core.util.DeferredSubscription.set(DeferredSubscription.java:71)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onSubscribe(FluxSubscribeOn.java:137)
	at reactor.core.subscriber.SignalEmitter.start(SignalEmitter.java:170)
	at reactor.core.publisher.FluxYieldingEmitter.subscribe(FluxYieldingEmitter.java:43)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:152)
	at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:169)
	at reactor.core.publisher.FluxSubscribeOn$SourceSubscribeTask.run(FluxSubscribeOn.java:371)
	at reactor.core.publisher.SchedulerGroup$ProcessorWorker.onNext(SchedulerGroup.java:922)
	at reactor.core.publisher.SchedulerGroup$ProcessorWorker.onNext(SchedulerGroup.java:886)
	at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:842)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by robertgmoss** [comment]
@nebhale fixed latest problem with similar fix to `OAuth2RestTemplateBuilder#setRequestFactory`

**Comment by nebhale** [comment]
@robertgmoss Can you please take a look at the latest snapshot?  I found a huge bug, there since the beginning of V2, that could possibly have been causing these issues.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
