### ISSUE TITLE
CF Logs - Jumbled stack trace

### ISSUE THREAD

**Issue by Selvaguru** [cloudfoundry/cf-java-client#462]
Consider the following stack trace,
```
2016-04-20T11:36:07.50+0530 [App/0]      ERR VError: No service matches jobscheduler
2016-04-20T11:36:07.50+0530 [App/0]      ERR     at Object.getServices (/home/vcap/app/node_modules/xsenv/lib/xsservices.js:58:17)
2016-04-20T11:36:07.50+0530 [App/0]      ERR     at Object.<anonymous> (/home/vcap/app/index.js:17:22)
2016-04-20T11:36:07.50+0530 [App/0]      ERR     at Module._compile (module.js:435:26)
2016-04-20T11:36:07.50+0530 [App/0]      ERR     at Object.Module._extensions..js (module.js:442:10)
2016-04-20T11:36:07.50+0530 [App/0]      ERR     at Module.load (module.js:356:32)
2016-04-20T11:36:07.50+0530 [App/0]      ERR     at Function.Module._load (module.js:311:12)
2016-04-20T11:36:07.50+0530 [App/0]      ERR     at Function.Module.runMain (module.js:467:10)
2016-04-20T11:36:07.50+0530 [App/0]      ERR     at startup (node.js:136:18)
2016-04-20T11:36:07.50+0530 [App/0]      ERR     at node.js:963:3
```
The above logs are from cf cli. If we use cf-java-client library,
```
6508af07-5962-44b5-8a26-8dc8b8965d7b [Wed Apr 20 11:36:07 IST 2016]           throw new VError('No service matches %s', key); (STDERR, App)
6508af07-5962-44b5-8a26-8dc8b8965d7b [Wed Apr 20 11:36:07 IST 2016]     at Object.getServices (/home/vcap/app/node_modules/xsenv/lib/xsservices.js:58:17) (STDERR, App)
6508af07-5962-44b5-8a26-8dc8b8965d7b [Wed Apr 20 11:36:07 IST 2016] VError: No service matches jobscheduler (STDERR, App)
6508af07-5962-44b5-8a26-8dc8b8965d7b [Wed Apr 20 11:36:07 IST 2016]     at Object.Module._extensions..js (module.js:442:10) (STDERR, App)
6508af07-5962-44b5-8a26-8dc8b8965d7b [Wed Apr 20 11:36:07 IST 2016]     at startup (node.js:136:18) (STDERR, App)
````

We get the following result. The order of stack trace is not maintained.

**Comment by nebhale** [comment]
@Selvaguru Which version of the library are you seeing this in?

**Comment by Selvaguru** [comment]
@nebhale it was 1.1.4

**Comment by nebhale** [comment]
With the imminent release of v2 of the library, we've shifted all efforts off of v1 development.  We don't plan on fixing this issue and encourage you to take a look at the V2 milestones and snapshots.  

At the moment, using the `CloudFoundryOperations` type in V2, `recentLogs()` returns properly ordered entries since the contents are finite and sortable.  `streamLogs()` is a bit more difficult since it's open-ended but we're looking to add a "windowed" sorting algorithm there.  Our goal is to get it in for the V2 release at the beginning of August, but it might slip to a later minor release as an addition.
