### ISSUE TITLE
Unexpected exception in the selector loop when build SpringCloudFoundryClient

### ISSUE THREAD

**Issue by ybshen** [cloudfoundry/cf-java-client#485]
```
警告: Unexpected exception in the selector loop.
java.io.IOException: 无法立即完成一个非阻止性套接字操作。
	at sun.nio.ch.SocketDispatcher.close0(Native Method)
	at sun.nio.ch.SocketDispatcher.close(SocketDispatcher.java:63)
	at sun.nio.ch.SocketChannelImpl.kill(SocketChannelImpl.java:878)
	at sun.nio.ch.WindowsSelectorImpl.implDereg(WindowsSelectorImpl.java:588)
	at sun.nio.ch.SelectorImpl.processDeregisterQueue(SelectorImpl.java:149)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:142)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:638)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:324)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by nebhale** [comment]
Netty upgraded in 5458492.  As the error occurs in that part of the stack, this should solve the issue.
