### ISSUE TITLE
SpringCloudFoundryClient Memory Leak

### ISSUE THREAD

**Issue by ybshen** [cloudfoundry/cf-java-client#495]
when I create app with SpringCloudfoundryClient,I found  my application occupy a lot of memory and cpu.and throw exception as below
```
io.netty.channel.unix.Errors$NativeIoException: epoll_ctl() failed: No such file or directory
        at io.netty.channel.unix.Errors.newIOException(Errors.java:115)
        at io.netty.channel.epoll.Native.epollCtlMod(Native.java:128)
        at io.netty.channel.epoll.EpollEventLoop.modify(EpollEventLoop.java:145)
        at io.netty.channel.epoll.AbstractEpollChannel.modifyEvents(AbstractEpollChannel.java:18
        at io.netty.channel.epoll.AbstractEpollChannel.clearFlag(AbstractEpollChannel.java:81)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.clearEpollRdHup(Abstr
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollRdHupReady(Abstr
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:374)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:283)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.ja
        at java.lang.Thread.run(Thread.java:745)`
```

**Comment by nebhale** [comment]
The `epoll_ctl()` issue comes from the `reactor-netty` issue and is currently being worked on.  While it is annoying and will result in failed requests, we do not believe that it has a significant effect on memory or CPU usage (other than driving the aforementioned failures).  If you are seeing large memory growth in your application, I'd keep digging until you've got conclusive proof that it is coming out of the Java Client or Reactor.

/cc @smaldini

**Comment by nebhale** [comment]
Recent changes to `reactor-netty` should have solved this issue.  Can you please re-test and let me know if you're still seeing issues.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
