### ISSUE TITLE
java.net.UnknownHostException behind Corporate proxy

### ISSUE THREAD

**Issue by omsoni** [cloudfoundry/cf-java-client#516]
I am using cf-java-client to connect to corporate cloudfoundry instance. Below is the the bean definition:

	@Bean
	CloudFoundryClient cloudFoundryClient(@Value("${xxxx.endpoint}") String host,
	                                      @Value("${credentials.username}") String username,
	                                      @Value("${credentials.password}") String password,
	                                      @Value("${proxy.skipSslValidation:false}") Boolean skipSslValidation,
                                          @Value("${proxy.host}") String proxyHost,
                                          @Value("${proxy.password}") String proxyPassword,
                                          @Value("${proxy.port}") Integer proxyPort,
                                          @Value("${proxy.username}") String proxyUsername) {
		System.out.println(" host is:  " + host );
	    return SpringCloudFoundryClient.builder()
	            .host(host)
	            .username(username)
	            .password(password)
	            .skipSslValidation(skipSslValidation)
	            .proxyHost(proxyHost)
	            .proxyPort(proxyPort)
	            .proxyUsername(proxyUsername)	 
	            .proxyPassword(proxyPassword)
	            .build();
	}
I get following error. I also tried setting proxy at JVM level.

```
org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.cloudfoundry.client.CloudFoundryClient]: Factory method 'cloudFoundryClient' threw exception; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://<<hostname>>:443/v2/info": <<hostname>>; nested exception is java.net.UnknownHostException: <<hostname>>
```
This seems like fairly common requirement. What am I missing ?

Thanks,
Om

**Comment by Zteve** [comment]
@omsoni Hi Om,
Two questions: did the `System.out.println(" host is:  " + host );` print out what you expected?  And not `" host is:  <>"` :-D ?

and... did you get a stacktrace by any chance?

**Comment by omsoni** [comment]
:) of course it did. I removed the host to keep it private. 

Below is the stacktrace:

org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.cloudfoundry.client.CloudFoundryClient]: Factory method 'cloudFoundryClient' threw exception; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.system.somecloud.somehost.io:443/v2/info": api.system.somecloud.somehost.io; nested exception is java.net.UnknownHostException: api.system.somecloud.somehost.io
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) ~[spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) ~[spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.test.SpringApplicationContextLoader.loadContext(SpringApplicationContextLoader.java:98) [spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:228) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:230) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:249) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193) [spring-test-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.1.jar:2.18.1]
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.somecompany.somehost.connector.somehostConnector com.somecompany.somehost.connector.somehostConnectorAppTests.pdxConn; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'somehostConnector': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.cloudfoundry.operations.CloudFoundryOperations com.somecompany.somehost.connector.somehostConnector.cfops; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cloudFoundryOperations' defined in com.somecompany.somehost.connector.AppConfig: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.cloudfoundry.client.CloudFoundryClient]: Error creating bean with name 'cloudFoundryClient' defined in com.somecompany.somehost.connector.AppConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.cloudfoundry.client.CloudFoundryClient]: Factory method 'cloudFoundryClient' threw exception; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.system.somecloud.somehost.io:443/v2/info": api.system.somecloud.somehost.io; nested exception is java.net.UnknownHostException: api.system.somecloud.somehost.io; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudFoundryClient' defined in com.somecompany.somehost.connector.AppConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.cloudfoundry.client.CloudFoundryClient]: Factory method 'cloudFoundryClient' threw exception; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.system.somecloud.somehost.io:443/v2/info": api.system.somecloud.somehost.io; nested exception is java.net.UnknownHostException: api.system.somecloud.somehost.io

CF CLI connects just fine, I have deployed quite a few apps there.
It is very likely a proxy setup issue. Any help/guidance appreciated.

As I mentioned in last post, I also tried System.setProperty("http.proxyHost") +++

Thanks for quick response.

**Comment by nebhale** [comment]
Yes, this is currently a known issue (#479 as mentioned above) around where the host names are resolved in proxy situations.  We're waiting on a change to `reactor-netty` to fix this at the lowest possible level.

**Comment by nebhale** [comment]
I'm going to close this out as a duplicate.  Please track #479 for resolution.
