### ISSUE TITLE
Failed to instantiate [org.cloudfoundry.client.CloudFoundryClient]: Factory method 'cloudFoundryClient' threw exception; nested exception is java.lang.NoClassDefFoundError: reactor/core/Loopback

### ISSUE THREAD

**Issue by mandeepkhambay** [cloudfoundry/cf-java-client#529]
With the latest I am getting the below exception. 

I noticed in the wiki page cloudfoundry-client-spring has been replaced by cloudfoundry-client-reactor. Also lot of changes on how to setup CloudFoundryClient is configured. 

Is there any backwards compatible code? Will these changes be part of your Release coming up shortly?

Thanks,

Mandeep

```
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.cloudfoundry.client.CloudFoundryClient]: Factory method 'cloudFoundryClient' threw exception; nested exception is java.lang.NoClassDefFoundError: reactor/core/Loopback
2016-07-20T09:00:16.61-0700 [App/0]      ERR 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
2016-07-20T09:00:16.61-0700 [App/0]      ERR 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:464)
2016-07-20T09:00:16.61-0700 [App/0]      ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
2016-07-20T09:00:16.61-0700 [App/0]      ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
2016-07-20T09:00:16.61-0700 [App/0]      ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
2016-07-20T09:00:16.61-0700 [App/0]      ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
```

**Comment by nebhale** [comment]
Since we are still in milestones and have not made it to a release, all APIs are candidates for breaking changes.  Once the release is out, we will follow [semver](http://semver.org) meaning that all public APIs (of which, these qualify) will maintain compatibility until a major version release.

**Comment by mandeepkhambay** [comment]
Thanks Ben. I have modified based on your recent changes, everything is working now.
