### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by andreaturli** [cloudfoundry/cf-java-client#541]
hi all,

I think the readme is not in sync. I'm trying to follow the basic instructions to list applications is a very simple example (see [gist](https://gist.github.com/andreaturli/4e2f4fc8df0b937daf6cb1565bb2128a)) but the main hangs forever. Looks like DefaultConnectionContext is not closed or something.

Can you suggest what can I try instead?

I'm using
```
    <dependencies>
        <dependency>
            <groupId>org.cloudfoundry</groupId>
            <artifactId>cloudfoundry-client-reactor</artifactId>
            <version>2.0.0.BUILD-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.cloudfoundry</groupId>
            <artifactId>cloudfoundry-operations</artifactId>
            <version>2.0.0.BUILD-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.0.0.RC1</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.ipc</groupId>
            <artifactId>reactor-netty</artifactId>
            <version>0.5.0.BUILD-SNAPSHOT</version>
        </dependency>
```

**Comment by nebhale** [comment]
There was a bug in `reactor-netty` that created non-daemon threads by default.  This is fixed in the latest snapshot.  Take note that you're likely to have *exactly the opposite* problem now; your application will exit before the responses are received.  You'll need to make use of a latch to ensure that your application stays alive until the response is complete.

**Comment by andreaturli** [comment]
thanks @nebhale, but updating my deps doesn't help. Same issue.

**Comment by nebhale** [comment]
@andreaturli Can you please include the results of `kill -3` in this issue?

**Comment by andreaturli** [comment]
```
ApplicationSummary{diskQuota=1024, id=52f91f0f-9ce6-4e27-b00d-ef9f530ea87d, instances=1, memoryLimit=1024, name=test-service-broker, requestedState=STARTED, runningInstances=1, urls=[test-service-broker.cfdev-cloudsoft.com]}
ApplicationSummary{diskQuota=1024, id=177902ab-f56e-4fb3-9d24-9c847046a182, instances=1, memoryLimit=1024, name=AMP, requestedState=STARTED, runningInstances=1, urls=[amp.cfdev-cloudsoft.com]}
ApplicationSummary{diskQuota=1024, id=e791d53a-d087-4715-a32f-e4e8e8f01409, instances=1, memoryLimit=128, name=simple-go-web-app, requestedState=STARTED, runningInstances=1, urls=[simple-go-web-app.cfdev-cloudsoft.com]}
ApplicationSummary{diskQuota=1024, id=ca081dcf-9ece-4d93-8971-c84da480b95b, instances=1, memoryLimit=1024, name=Cloudsoft Service Broker, requestedState=STARTED, runningInstances=0, urls=[cloudsoft-service-broker.cfdev-cloudsoft.com]}
ApplicationSummary{diskQuota=1024, id=81287266-e229-40cb-870e-7cc0f932cef0, instances=1, memoryLimit=1024, name=Brooklyn-Service-Broker, requestedState=STARTED, runningInstances=1, urls=[brooklyn-service-broker.cfdev-cloudsoft.com]}

2016-07-31 18:32:53
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.92-b14 mixed mode):

"timer-1" #26 daemon prio=5 os_prio=31 tid=0x00007fef3c9d4000 nid=0x3d07 waiting on condition [0x0000700000e3d000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c04fab20> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"reactor-tcp-client-io-12" #25 prio=5 os_prio=31 tid=0x00007fef3d191800 nid=0x7603 runnable [0x000070000237f000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c0502ca8> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006c0502cc8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c0502c58> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)

"reactor-tcp-client-io-11" #24 prio=5 os_prio=31 tid=0x00007fef3c9d3000 nid=0x7403 runnable [0x000070000227c000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c050a5b8> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006c050a5d8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c050a568> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)

"reactor-tcp-client-io-10" #23 prio=5 os_prio=31 tid=0x00007fef3d13a000 nid=0x7203 runnable [0x0000700002179000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c05125a8> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006c05125c8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c0512558> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)

"reactor-tcp-client-io-9" #22 prio=5 os_prio=31 tid=0x00007fef3a240800 nid=0x7003 runnable [0x0000700002076000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c050a7e8> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006c050a808> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c050a798> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)

"DestroyJavaVM" #21 prio=5 os_prio=31 tid=0x00007fef3a1da000 nid=0x1703 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"threadDeathWatcher-2-1" #20 daemon prio=1 os_prio=31 tid=0x00007fef3996e800 nid=0x6e03 waiting on condition [0x0000700001f73000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

"reactor-tcp-client-io-8" #19 prio=5 os_prio=31 tid=0x00007fef3c974000 nid=0x6c03 runnable [0x0000700001e70000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c0512868> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006c0512888> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c0512818> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)

"reactor-tcp-client-io-7" #18 prio=5 os_prio=31 tid=0x00007fef3d14e000 nid=0x6a03 runnable [0x0000700001d6d000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c051a710> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006c051a730> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c051a6c0> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)

"reactor-tcp-client-io-6" #17 prio=5 os_prio=31 tid=0x00007fef3d157800 nid=0x6803 runnable [0x0000700001c6a000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c0522578> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006c0522598> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c0522528> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)

"reactor-tcp-client-io-5" #16 prio=5 os_prio=31 tid=0x00007fef3d106000 nid=0x6603 runnable [0x0000700001b67000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c051a940> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006c051a960> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c051a8f0> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)

"reactor-tcp-client-io-4" #15 prio=5 os_prio=31 tid=0x00007fef39941800 nid=0x6403 runnable [0x0000700001a64000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c05324c0> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006c05324e0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c0532470> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)

"reactor-tcp-client-io-3" #14 prio=5 os_prio=31 tid=0x00007fef39a32800 nid=0x6203 runnable [0x0000700001961000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c051ac00> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006c051ac20> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c051abb0> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)

"reactor-tcp-client-io-2" #13 prio=5 os_prio=31 tid=0x00007fef39a31800 nid=0x6003 runnable [0x000070000185e000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c05227a8> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006c05227c8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c0522758> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)

"reactor-tcp-client-io-1" #12 prio=5 os_prio=31 tid=0x00007fef398f3000 nid=0x5e0f runnable [0x000070000175b000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c051eac8> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006c0520bb8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c051e998> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)

"Monitor Ctrl-Break" #10 daemon prio=5 os_prio=31 tid=0x00007fef3c855800 nid=0x5703 runnable [0x0000700001658000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at com.intellij.rt.execution.application.AppMain$1.run(AppMain.java:79)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #9 daemon prio=9 os_prio=31 tid=0x00007fef3b00b000 nid=0x5303 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x00007fef3d031800 nid=0x5103 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007fef39815000 nid=0x4f03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007fef3a00e800 nid=0x4d03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007fef3c00f000 nid=0x4b03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007fef3c802800 nid=0x3e0f waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007fef3c006000 nid=0x3803 in Object.wait() [0x0000700000d3a000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0523320> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c0523320> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007fef3d806000 nid=0x3603 in Object.wait() [0x0000700000c37000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0518fb0> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000006c0518fb0> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=31 tid=0x00007fef3b007000 nid=0x3403 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007fef3c807000 nid=0x2403 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007fef3b002000 nid=0x2603 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007fef3b003000 nid=0x2803 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007fef3b003800 nid=0x2a03 runnable 

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007fef3a800800 nid=0x2c03 runnable 

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007fef3d800000 nid=0x2e03 runnable 

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007fef3d801000 nid=0x3003 runnable 

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007fef3d801800 nid=0x3203 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007fef3a816800 nid=0x5503 waiting on condition 

JNI global references: 477

Heap
 PSYoungGen      total 76288K, used 5895K [0x000000076ab00000, 0x0000000770000000, 0x00000007c0000000)
  eden space 65536K, 8% used [0x000000076ab00000,0x000000076b0c1c28,0x000000076eb00000)
  from space 10752K, 0% used [0x000000076f580000,0x000000076f580000,0x0000000770000000)
  to   space 10752K, 0% used [0x000000076eb00000,0x000000076eb00000,0x000000076f580000)
 ParOldGen       total 88064K, used 15774K [0x00000006c0000000, 0x00000006c5600000, 0x000000076ab00000)
  object space 88064K, 17% used [0x00000006c0000000,0x00000006c0f67998,0x00000006c5600000)
 Metaspace       used 21168K, capacity 21736K, committed 21808K, reserved 1069056K
  class space    used 2501K, capacity 2658K, committed 2688K, reserved 1048576K
```

I've issued `kill -3` right after the applications have been printed.

**Comment by nebhale** [comment]
This doesn't appear to be the latest snapshot of `reactor-netty`. The give away is that `reactor-tcp-client-io-##` aren't daemon threads.

Just to confirm @smaldini, we've seen a snapshot with this change?

**Comment by andreaturli** [comment]
For completeness I'm using 
```
Downloading: http://repo.spring.io/snapshot/io/projectreactor/ipc/reactor-netty/0.5.0.BUILD-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.spring.io/milestone/io/projectreactor/ipc/reactor-netty/0.5.0.BUILD-SNAPSHOT/maven-metadata.xml
Downloaded: http://repo.spring.io/snapshot/io/projectreactor/ipc/reactor-netty/0.5.0.BUILD-SNAPSHOT/maven-metadata.xml (2 KB at 5.1 KB/sec)
Downloading: http://repo.spring.io/snapshot/io/projectreactor/ipc/reactor-netty/0.5.0.BUILD-SNAPSHOT/reactor-netty-0.5.0.BUILD-20160730.234846-37.pom
Downloaded: http://repo.spring.io/snapshot/io/projectreactor/ipc/reactor-netty/0.5.0.BUILD-SNAPSHOT/reactor-netty-0.5.0.BUILD-20160730.234846-37.pom (4 KB at 9.5 KB/sec)
```

**Comment by andreaturli** [comment]
any updates on this? thanks!

**Comment by nebhale** [comment]
The [change](https://github.com/reactor/reactor-ipc/commit/15814c58793c4be08f9bbe5b2b079457195a5461) was made to Reactor Netty on July 29 so any snapshot after that will not have all threads `daemon` by default.  If you're not seeing that, I don't believe that you're actually running against the snapshots you think you are.  The code change is pretty clear and the thread dump you're showing doesn't contain that change.

**Comment by andreaturli** [comment]
thanks @nebhale, for some reason maven was still picking a `reactor-netty` from July 27.
Using Aug 8 version, fix the problem.
