### ISSUE TITLE
Pushing an empty Path

### ISSUE THREAD

**Issue by kiuby88** [cloudfoundry/cf-java-client#545]
Hi

When I tried to push an application using an empty application path:
```
operations.applications()
                .push(PushApplicationRequest.builder()
                        .buildpack(BUILDPACK)
                        .name(applicationName)
                        .application(Paths.get(""))
                        .memory(MEMORY)
                        .diskQuota(DISK)
                        .instances(INSTANCES)
                        .host(MY_HOST)
                        .noHostname(false)
                        .noStart(false)
                        .healthCheckType(ApplicationHealthCheck.PORT)
                        .build());
```

And I obtained the following strange error:
```
Exception in thread "main" java.util.concurrent.ExecutionException: org.cloudfoundry.client.v2.CloudFoundryException: UnknownError(10001): An unknown error occurred.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at PushArtifactMain.main(PushArtifactMain.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: org.cloudfoundry.client.v2.CloudFoundryException: UnknownError(10001): An unknown error occurred.
	at org.cloudfoundry.util.JobUtils.getError(JobUtils.java:67)
	at reactor.core.publisher.MonoThenApply$MonoThenApplyManager.onNext(MonoThenApply.java:99)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:118)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:91)
	at reactor.core.publisher.FluxRepeatWhen$RepeatWhenMainSubscriber.onNext(FluxRepeatWhen.java:128)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:176)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:118)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:235)
	at reactor.core.publisher.FluxResume$ResumeSubscriber.onNext(FluxResume.java:75)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:173)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:131)
	at reactor.core.publisher.Operators$DeferredScalarSubscriber.complete(Operators.java:797)
	at reactor.core.publisher.MonoThenApply$MonoThenApplyManager$SecondSubscriber.onNext(MonoThenApply.java:204)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:125)
	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:320)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:115)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:390)
	at reactor.core.publisher.Operators$DeferredScalarSubscriber.complete(Operators.java:797)
	at reactor.core.publisher.MonoReduce$ReduceSubscriber.onComplete(MonoReduce.java:152)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:157)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onComplete(FluxSubscribeOn.java:137)
	at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.drain(NettyChannelHandler.java:696)
	at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.request(NettyChannelHandler.java:772)
	at reactor.core.publisher.Operators$DeferredSubscription.set(Operators.java:598)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onSubscribe(FluxSubscribeOn.java:117)
	at reactor.ipc.netty.common.NettyChannelHandler.subscribe(NettyChannelHandler.java:543)
	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:59)
	at reactor.core.publisher.FluxSubscribeOn$SourceSubscribeTask.run(FluxSubscribeOn.java:235)
	at reactor.core.scheduler.ExecutorScheduler$ExecutorTrackedRunnable.run(ExecutorScheduler.java:134)
	at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)
```

I have opened this PR because I was expected to find something similar to `        java.nio.file.FileSystemNotFoundException`, which is thrown when the pushed application path does not exist. I do not know if it makes sense for you, but it looks that the source of the confusion could be that `java.nio.file.Files.exists(Paths.get(""))` returns `true`.
 
Thanks a lot!

**Comment by nebhale** [comment]
`Paths.get("")` is a legal which is why `Files.exists()` returns true when presented.  A test that looks like `System.out.println(Paths.get("").toAbsolutePath());` shows that it represents the current working directory.  What has happened is that you've uploaded the entire working directory that you ran from and the server didn't believe that it was a stage-able application and returned a failure.

**Comment by Zteve** [comment]
@nebhale Agreed that this is a valid parameter, but the error seems somewhat vague and unhelpful, doesn't it? Perhaps this should be raised against CloudFoundry instead?

What does the CLI do if I pass in `-p ''`? (Can't test `cf push` at home atm.)

**Comment by nebhale** [comment]
@Zteve I'd bet that if you looked at the logs behind the staging attempt, you'd see a reasonable error there.  My guess is that you'd see a `detect` attempt by the buildpack or buildpacks, but that the "application" wasn't something that could be properly handled, so staging would fail.  That that is represented by an unhelpful REST error would seem to be a CF bug.
