### ISSUE TITLE
hostname can't be null

### ISSUE THREAD

**Issue by snowch** [cloudfoundry/cf-java-client#552]
I'm trying to use the example on the README:

```
    def apiHost = 'https://api.ng.bluemix.net'
    def username = 'xxxxx'
    def password = 'xxxxxx'
    def organization = 'xxx'
    def space = 'xxx'

    def connectionContext = DefaultConnectionContext.builder()
        .apiHost(apiHost)
        .build()

    def tokenProvider = PasswordGrantTokenProvider.builder()
        .password(password)
        .username(username)
        .build()

    def cloudFoundryClient = ReactorCloudFoundryClient.builder()
        .connectionContext(connectionContext)
        .tokenProvider(tokenProvider)
        .build()

    def dopplerClient = ReactorDopplerClient.builder()
        .connectionContext(connectionContext)
        .tokenProvider(tokenProvider)
        .build()

    def uaaClient = ReactorUaaClient.builder()
        .connectionContext(connectionContext)
        .tokenProvider(tokenProvider)
        .build()

    def cloudFoundryOperations = DefaultCloudFoundryOperations.builder()
        .cloudFoundryClient(cloudFoundryClient)
        .dopplerClient(dopplerClient)
        .uaaClient(uaaClient)
        .organization(organization)
        .space(space)
        .build()

    cloudFoundryOperations.organizations()
        .list()
        .map { org -> organization.name }
        .subscribe { println }
```

Results in

```
Caused by: reactor.core.Exceptions$BubblingException: java.lang.IllegalArgumentException: hostname can't be null
        at reactor.core.Exceptions.bubble(Exceptions.java:96)
        at reactor.core.publisher.Operators.onErrorDropped(Operators.java:317)
        at reactor.core.publisher.LambdaSubscriber.onError(LambdaSubscriber.java:126)
        at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
        at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:758)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:520)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:500)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onError(FluxFlatMap.java:480)
        at reactor.core.publisher.MonoFlatMap$FlattenSubscriber.onError(MonoFlatMap.java:166)
        at reactor.core.publisher.FluxResume$ResumeSubscriber.onError(FluxResume.java:104)
        at reactor.core.publisher.Operators.error(Operators.java:208)
        at reactor.core.publisher.MonoError.subscribe(MonoError.java:75)
        at reactor.core.publisher.FluxResume$ResumeSubscriber.onError(FluxResume.java:101)
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:197)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:145)
        at reactor.core.publisher.MonoThenApply$MonoThenApplyManager.onError(MonoThenApply.java:146)
        at reactor.core.publisher.MonoThenApply$MonoThenApplyManager.secondError(MonoThenApply.java:166)
        at reactor.core.publisher.MonoThenApply$MonoThenApplyManager$SecondSubscriber.onError(MonoThenApply.java:212)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:193)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:193)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:193)
        at reactor.core.publisher.Operators.error(Operators.java:208)
        at reactor.ipc.netty.http.MonoHttpClientChannel.lambda$subscribe$46(MonoHttpClientChannel.java:122)
        at reactor.core.publisher.LambdaSubscriber.onError(LambdaSubscriber.java:123)
        at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onError(FluxRetryPredicate.java:100)
        at reactor.core.publisher.Operators.error(Operators.java:208)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:56)
        at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.resubscribe(FluxRetryPredicate.java:123)
        at reactor.core.publisher.MonoRetryPredicate.subscribe(MonoRetryPredicate.java:54)
        at reactor.core.publisher.Mono.subscribeWith(Mono.java:2304)
        at reactor.core.publisher.Mono.subscribe(Mono.java:2266)
        at reactor.core.publisher.Mono.subscribe(Mono.java:2244)
        at reactor.ipc.netty.http.MonoHttpClientChannel.subscribe(MonoHttpClientChannel.java:122)
        at reactor.core.publisher.MonoPeek.subscribe(MonoPeek.java:98)
        at reactor.core.publisher.MonoPeek.subscribe(MonoPeek.java:98)
        at reactor.core.publisher.MonoPeek.subscribe(MonoPeek.java:98)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:66)
        at reactor.core.publisher.MonoThenApply$MonoThenApplyManager.onNext(MonoThenApply.java:132)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1413)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:185)
        at reactor.core.publisher.MonoThenApply$MonoThenApplyManager.onSubscribe(MonoThenApply.java:83)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:99)
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:49)
        at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:69)
        at reactor.core.publisher.MonoThenApply.subscribe(MonoThenApply.java:57)
        at reactor.core.publisher.MonoThenApply.subscribe(MonoThenApply.java:57)
        at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:69)
        at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:95)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:66)
        at reactor.core.publisher.MonoOtherwise.subscribe(MonoOtherwise.java:47)
        at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:39)
        at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:101)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:175)
        at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:36)
        at reactor.core.publisher.FluxMap.subscribe(FluxMap.java:72)
        at reactor.core.publisher.FluxMap.subscribe(FluxMap.java:72)
        at reactor.core.publisher.Flux.subscribe(Flux.java:4547)
        at reactor.core.publisher.Flux.subscribe(Flux.java:4484)
        at bluemix_deploy_8mmwl9h9krh0ahvarkr544pn8$_run_closure3.doCall(/Users/snowch/Repos/BigInsights-on-Apache-Hadoop/examples/OozieWorkflowSparkGroovy/bluemix-deploy.gradle:79)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:137)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:522)
        at org.gradle.api.internal.project.AbstractProject.task(AbstractProject.java:927)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:374)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:169)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
        at bluemix_deploy_8mmwl9h9krh0ahvarkr544pn8.run(/Users/snowch/Repos/BigInsights-on-Apache-Hadoop/examples/OozieWorkflowSparkGroovy/bluemix-deploy.gradle:39)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
        ... 50 more
```

**Comment by twoseat** [comment]
Hi @snowch - can you try setting apiHost to `api.ng.bluemix.net` (no `https://`) and try again, then let me know what happens? Thanks!

**Comment by nebhale** [comment]
I'm almost sure that this is the problem.  I've tested against BlueMix recently, so I'm pretty sure it works. What we haven't done is enforced that only a host name is allowed during configuration.  Let's repurpose this issue to enforce that.
