### ISSUE TITLE
connection close by remote host

### ISSUE THREAD

**Issue by ctatineni** [cloudfoundry/cf-java-client#564]
Followed cf-java-client git hub documentation and created a client, i was able to connect to cloud foundry , after some time i am getting the below error.

java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_51]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_51]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_51]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_51]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_51]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343) ~[netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118) ~[netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

**Comment by nebhale** [comment]
That seems like an issue with the server not the client, no?  What exactly do you expect to happen on the client side when the server forcibly closes the connection?

**Comment by ctatineni** [comment]
Thanks it was an issue with CF server, able to resolve this.now i am getting EOF exception, similar to issue #502 , i am not sure what version has this fix, i am currently using  2.0.0.RELEASE , may i know what version has this fix.

**Comment by ctatineni** [comment]
Exception stack trace incase if needed
reactor.core.Exceptions$BubblingException: java.io.EOFException
	at reactor.core.Exceptions.bubble(Exceptions.java:96) ~[reactor-core-3.0.0.RELEASE.jar:na]
	at reactor.core.publisher.Operators.onErrorDropped(Operators.java:317) ~[reactor-core-3.0.0.RELEASE.jar:na]
	at reactor.core.publisher.LambdaSubscriber.onError(LambdaSubscriber.java:126) ~[reactor-core-3.0.0.RELEASE.jar:na]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onError(FluxSubscribeOn.java:127) ~[reactor-core-3.0.0.RELEASE.jar:na]
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.0.0.RELEASE.jar:na]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:111) ~[reactor-core-3.0.0.RELEASE.jar:na]
	at reactor.core.publisher.MonoFlatMap$FlattenSubscriber$InnerSubscriber.onNext(MonoFlatMap.java:194) ~[reactor-core-3.0.0.RELEASE.jar:na]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.0.0.RELEASE.jar:na]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:126) ~[reactor-core-3.0.0.RELEASE.jar:na]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onNext(FluxSubscribeOn.java:121) ~[reactor-core-3.0.0.RELEASE.jar:na]
	at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.next(NettyChannelHandler.java:601) ~[reactor-netty-0.5.0.RELEASE.jar:na]
	at reactor.ipc.netty.common.NettyChannelHandler.doRead(NettyChannelHandler.java:134) ~[reactor-netty-0.5.0.RELEASE.jar:na]
	at reactor.ipc.netty.http.NettyWebSocketClientHandler.channelRead(NettyWebSocketClientHandler.java:134) ~[reactor-netty-0.5.0.RELEASE.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1066) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) [netty-all-4.1.4.Final.jar:4.1.4.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: java.io.EOFException: null
	at okio.RealBufferedSource.require(RealBufferedSource.java:59) ~[okio-1.8.0.jar:na]
	at com.squareup.wire.ProtoReader.beforeLengthDelimitedScalar(ProtoReader.java:387) ~[wire-runtime-2.2.0.jar:na]
	at com.squareup.wire.ProtoReader.readBytes(ProtoReader.java:258) ~[wire-runtime-2.2.0.jar:na]
	at com.squareup.wire.ProtoAdapter$13.decode(ProtoAdapter.java:391) ~[wire-runtime-2.2.0.jar:na]
	at com.squareup.wire.ProtoAdapter$13.decode(ProtoAdapter.java:381) ~[wire-runtime-2.2.0.jar:na]
	at org.cloudfoundry.dropsonde.events.LogMessage$ProtoAdapter_LogMessage.decode(LogMessage.java:310) ~[cloudfoundry-client-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.cloudfoundry.dropsonde.events.LogMessage$ProtoAdapter_LogMessage.decode(LogMessage.java:277) ~[cloudfoundry-client-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.cloudfoundry.dropsonde.events.Envelope$ProtoAdapter_Envelope.decode(Envelope.java:572) ~[cloudfoundry-client-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.cloudfoundry.dropsonde.events.Envelope$ProtoAdapter_Envelope.decode(Envelope.java:499) ~[cloudfoundry-client-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.java:195) ~[wire-runtime-2.2.0.jar:na]
	at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.java:189) ~[wire-runtime-2.2.0.jar:na]
	at org.cloudfoundry.reactor.doppler.ReactorDopplerEndpoints.toEnvelope(ReactorDopplerEndpoints.java:66) ~[cloudfoundry-client-reactor-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.cloudfoundry.reactor.doppler.ReactorDopplerEndpoints$$Lambda$85/293326812.apply(Unknown Source) ~[na:na]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:109) ~[reactor-core-3.0.0.RELEASE.jar:na]
	... 39 common frames omitted
