### ISSUE TITLE
Apps stopped due to staging error  throws error on GetApplicationRequest call 

### ISSUE THREAD

**Issue by mohanpindyala** [cloudfoundry/cf-java-client#573]
Steps to repro. what is the work around for this.
1.App stopped due to staging error or crashed . 
2. Do a GetApplicationRequest.builder().name("somename")
                                                                      .build()
3. error 
```
2016-10-12T16:41:55.45-0700 [APP/0]      OUT org.cloudfoundry.client.v2.CloudFoundryException: CF-BuildpackCompileFailed(170004): App staging failed in the buildpack compile phase
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at org.cloudfoundry.reactor.client.CloudFoundryExceptionBuilder.lambda$build$0(CloudFoundryExceptionBuilder.java:52)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.MonoThenApply$MonoThenApplyManager.onNext(MonoThenApply.java:97)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:314)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:108)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:368)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:892)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.MonoReduce$ReduceSubscriber.onComplete(MonoReduce.java:149)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR Exception in thread "reactor-tcp-client-io-4" org.cloudfoundry.client.v2.CloudFoundryException: CF-BuildpackCompileFailed(170004): App staging failed in the buildpack compile phase
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at org.cloudfoundry.reactor.client.CloudFoundryExceptionBuilder.lambda$build$0(CloudFoundryExceptionBuilder.java:52)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onComplete(FluxSubscribeOn.java:160)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.core.publisher.MonoThenApply$MonoThenApplyManager.onNext(MonoThenApply.java:97)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.drain(NettyChannelHandler.java:696)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.request(NettyChannelHandler.java:772)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:136)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:129)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.ipc.netty.common.NettyChannelHandler.subscribe(NettyChannelHandler.java:543)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:59)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SourceSubscribeTask.run(FluxSubscribeOn.java:231)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.scheduler.ExecutorScheduler$ExecutorTrackedRunnable.run(ExecutorScheduler.java:136)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at java.lang.Thread.run(Thread.java:745)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT Caused by: reactor.ipc.netty.http.HttpException: HTTP request failed with code: 400
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 2016-10-12 23:41:55.454 ERROR 21 --- [tcp-client-io-4] c.m.a.pcf.utils.StatusNotifierScheduler  : failed to send notifications for apps {}
2016-10-12T16:41:55.45-0700 [APP/0]      OUT org.cloudfoundry.client.v2.CloudFoundryException: CF-BuildpackCompileFailed(170004): App staging failed in the buildpack compile phase
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at org.cloudfoundry.reactor.client.CloudFoundryExceptionBuilder.lambda$build$0(CloudFoundryExceptionBuilder.java:52)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.MonoThenApply$MonoThenApplyManager.onNext(MonoThenApply.java:97)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:314)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:108)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:368)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:892)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.MonoReduce$ReduceSubscriber.onComplete(MonoReduce.java:149)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onComplete(FluxSubscribeOn.java:160)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.drain(NettyChannelHandler.java:696)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.request(NettyChannelHandler.java:772)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:136)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:129)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.ipc.netty.common.NettyChannelHandler.subscribe(NettyChannelHandler.java:543)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:59)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SourceSubscribeTask.run(FluxSubscribeOn.java:231)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at reactor.core.scheduler.ExecutorScheduler$ExecutorTrackedRunnable.run(ExecutorScheduler.java:136)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT 	at java.lang.Thread.run(Thread.java:745)
2016-10-12T16:41:55.45-0700 [APP/0]      OUT Caused by: reactor.ipc.netty.http.HttpException: HTTP request failed with code: 400
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:314)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:108)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:368)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:892)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.core.publisher.MonoReduce$ReduceSubscriber.onComplete(MonoReduce.java:149)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onComplete(FluxSubscribeOn.java:160)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.drain(NettyChannelHandler.java:696)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.request(NettyChannelHandler.java:772)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:136)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:129)
2016-10-12T16:41:55.45-0700 [APP/0]      ERR 	at reactor.ipc.netty.common.NettyChannelHandler.subscribe(NettyChannelHandler.java:543)
```

**Comment by twoseat** [comment]
Hi @mohanpindyala thanks for reporting this. The latest snapshot should contain the fix, let us know how it goes.
