### ISSUE TITLE
Not possible to bind a service that has null values in credentials map

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-java-client#574]
I have a service with the credentials of:

```
"credentials": {
     "host": "home.domain.org",
     "path": "",
     "port": 443,
     "protocol": "https",
     "query": null,
     "ref": null,
     "url": "https://home.domain.org"
    }
```

When I attempt to bind this service to an application I get the error below.  This same service can be bound just fine with the go cli.  Perhaps the Objects.requireNonNull is unnecessary in ServiceBindingEntity.Builder.putAllCredentials?

```
org.cloudfoundry.reactor.util.JsonParsingException: Unable to parse JSON Payload
 at org.cloudfoundry.reactor.util.JsonCodec.lambda$decode$0(JsonCodec.java:42)
 at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
 at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:913)
 at reactor.core.publisher.MonoThenApply$MonoThenApplyManager$SecondSubscriber.onNext(MonoThenApply.java:201)
 at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
 at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:314)
 at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:108)
 at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:379)
 at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:913)
 at reactor.core.publisher.MonoReduce$ReduceSubscriber.onComplete(MonoReduce.java:149)
 at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152)
 at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onComplete(FluxSubscribeOn.java:136)
 at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.drain(NettyChannelHandler.java:696)
 at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.request(NettyChannelHandler.java:772)
 at reactor.core.publisher.Operators$DeferredSubscription.set(Operators.java:713)
 at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onSubscribe(FluxSubscribeOn.java:116)
 at reactor.ipc.netty.common.NettyChannelHandler.subscribe(NettyChannelHandler.java:543)
 at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:59)
 at reactor.core.publisher.FluxSubscribeOn$SourceSubscribeTask.run(FluxSubscribeOn.java:234)
 at reactor.core.scheduler.ExecutorScheduler$ExecutorTrackedRunnable.run(ExecutorScheduler.java:136)
 at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451)
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
 at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class org.cloudfoundry.client.v2.servicebindings.ServiceBindingEntity] value failed: credentials value (through reference chain: org.cloudfoundry.client.v2.applications.Json["resources"]->java.util.ArrayList[0]->org.cloudfoundry.client.v2.servicebindings.Json["entity"])
 at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapException(StdValueInstantiator.java:399)
 at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDelegate(StdValueInstantiator.java:262)
 at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1095)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
 at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
 at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:161)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
 at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1095)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
 at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
 at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:161)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
 at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1095)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
 at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
 at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2796)
 at org.cloudfoundry.reactor.util.JsonCodec.lambda$decode$0(JsonCodec.java:40)
 ... 24 common frames omitted
Caused by: java.lang.NullPointerException: credentials value
 at java.util.Objects.requireNonNull(Objects.java:228)
 at org.cloudfoundry.client.v2.servicebindings.ServiceBindingEntity$Builder.putAllCredentials(ServiceBindingEntity.java:534)
 at org.cloudfoundry.client.v2.servicebindings.ServiceBindingEntity.fromJson(ServiceBindingEntity.java:280)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.call1(AnnotatedMethod.java:125)
 at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDelegate(StdValueInstantiator.java:244)
 ... 49 common frames omitted
```

**Comment by nebhale** [comment]
@youngm Interesting that you've been able to generate this given [an issue over in the Java Buildpack](https://github.com/cloudfoundry/java-buildpack/issues/341#issuecomment-255165653).  Talking with @SocalNick it's unclear if this is even supported however as there's no robust spec, we can't really say that it isn't.  If you don't mind sharing, how were you even able to generate such a thing since `cups` won't do it.

**Comment by nebhale** [comment]
Oh sorry.  I'm totally wrong.  This is around our maps not allowing `null` values.  Yeah, let me get back to you on that.

**Comment by youngm** [comment]
Improved the description.

**Comment by nebhale** [comment]
Just a heads up that this will need to go into a 2.1.x release rather than a 2.0.x release as it'll be a pretty significant change to a dependency.

**Comment by youngm** [comment]
@nebhale Thanks for the heads up.
