### ISSUE TITLE
`cloudFoundryOperations.applications().getEvents()` errors out with some events

### ISSUE THREAD

**Issue by zilkey** [cloudfoundry/cf-java-client#578]
It appears that `cloudFoundryOperations.applications().getEvents()` errors out when encountering certain event types.

From what I can gather, events of type `audit.app.map-route` or `audit.app.create` cause the `getEvents()` call to error out.

The code that causes the error:

```java
cloudFoundryOperations
                    .applications()
                    .getEvents(GetApplicationEventsRequest
                            .builder()
                            .name(applicationName)
                            .maxNumberOfEvents(4)
                            .build())
                    .collectList()
                    .block();
```

> NOTE: I'm using the `.block()` just to make the demo easier, but it appears to work the same in the non-blocking version.

## Expected behavior

I expected the code to print out all of the events with no errors.

## Actual behavior

Got a `java.lang.NullPointerException`

## Steps to reproduce

I built a simple command-line app to demonstrate this.  It shows that getting certain events works, but not other events.

- Deploy a simple app to cloud foundry (I just downloaded a web app from start.spring.io for this test)
- Ensure that from the CLI the event log shows these events:

  ```
  Getting events for app events-test in org Galvanize Full Stack / space development as jeff@example.com...

  time                          event                 actor                description
  2016-11-16T15:05:16.00-0700   audit.app.update      jeff@example.com   state: STARTED
  2016-11-16T15:05:05.00-0700   audit.app.update      jeff@example.com
  2016-11-16T15:05:05.00-0700   audit.app.map-route   jeff@example.com
  2016-11-16T15:05:03.00-0700   audit.app.create      jeff@example.com   instances: 1, state: STOPPED, environment_json: PRIVATE DATA HIDDEN
  ```
- Download https://github.com/zilkey/cloud-foundry-api-events-bug
- Run it with:

  ```
  ./gradlew build && java -jar build/libs/cf-demo-0.0.1-SNAPSHOT.jar spring
    api.run.pivotal.io "Your organization" your-space user@example.com abc-someapikey-zyx your-app-name
  ```
- You should see a null pointer exception like so:

  ```
  Total time: 1.415 secs

    .   ____          _            __ _ _
   /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
  ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
   \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
    '  |____| .__|_| |_|_| |_\__, | / / / /
   =========|_|==============|___/=/_/_/_/
   :: Spring Boot ::        (v1.4.2.RELEASE)

  2016-11-16 15:43:46.817  INFO 53028 --- [           main] com.acme.CfDemoApplication               : Starting CfDemoApplication on Jeff-Dean.local with PID 53028 (/Users/galvanize/Downloads/cf-demo/build/libs/cf-demo-0.0.1-SNAPSHOT.jar started by galvanize in /Users/galvanize/Downloads/cf-demo)
  2016-11-16 15:43:46.820  INFO 53028 --- [           main] com.acme.CfDemoApplication               : No active profile set, falling back to default profiles: default
  2016-11-16 15:43:46.876  INFO 53028 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@28c97a5: startup date [Wed Nov 16 15:43:46 MST 2016]; root of context hierarchy
  2016-11-16 15:43:47.642  INFO 53028 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
  Getting 1 events
    ApplicationEvent{actor=jeff@galvanize.com, description=state: STARTED, event=audit.app.update, id=f5e42610-dfa0-40b6-9de6-277edfd903d3, time=Wed Nov 16 15:05:16 MST 2016}
  Getting 2 events
    ApplicationEvent{actor=jeff@galvanize.com, description=state: STARTED, event=audit.app.update, id=f5e42610-dfa0-40b6-9de6-277edfd903d3, time=Wed Nov 16 15:05:16 MST 2016}
    ApplicationEvent{actor=jeff@galvanize.com, description=, event=audit.app.update, id=3d5474db-2139-408d-a976-dcddcf9e7cab, time=Wed Nov 16 15:05:05 MST 2016}
  Getting 3 events
  2016-11-16 15:43:54.001  INFO 53028 --- [           main] utoConfigurationReportLoggingInitializer :

  Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
  2016-11-16 15:43:54.009 ERROR 53028 --- [           main] o.s.boot.SpringApplication               : Application startup failed

  java.lang.IllegalStateException: Failed to execute CommandLineRunner
  	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:803) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
  	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
  	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
  	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
  	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
  	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
  	at com.acme.CfDemoApplication.main(CfDemoApplication.java:30) [classes!/:na]
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
  	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
  	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [cf-demo-0.0.1-SNAPSHOT.jar:na]
  	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [cf-demo-0.0.1-SNAPSHOT.jar:na]
  	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [cf-demo-0.0.1-SNAPSHOT.jar:na]
  	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [cf-demo-0.0.1-SNAPSHOT.jar:na]
  Caused by: java.lang.NullPointerException: null
  	at org.cloudfoundry.operations.applications.DefaultApplications.getMetadataRequest(DefaultApplications.java:701) ~[cloudfoundry-operations-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
  	at org.cloudfoundry.operations.applications.DefaultApplications.convertToApplicationEvent(DefaultApplications.java:509) ~[cloudfoundry-operations-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
  	at org.cloudfoundry.operations.applications.DefaultApplications$$Lambda$79/1615056168.apply(Unknown Source) ~[na:na]
  	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:109) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.MonoFlatMap$FlattenSubscriber$InnerSubscriber.onNext(MonoFlatMap.java:194) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxTake$TakeSubscriber.onNext(FluxTake.java:136) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:661) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:541) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:1072) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:95) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:59) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:385) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.MonoFlatMap$FlattenSubscriber$InnerSubscriber.onNext(MonoFlatMap.java:194) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:358) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:587) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:216) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxBuffer$BufferExactSubscriber.onComplete(FluxBuffer.java:179) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:177) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:96) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxBuffer.subscribe(FluxBuffer.java:74) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxFlattenIterable.subscribe(FluxFlattenIterable.java:101) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.MonoFlatMap$FlattenSubscriber.onNext(MonoFlatMap.java:157) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxResume$ResumeSubscriber.onNext(FluxResume.java:74) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:164) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:126) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:892) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.MonoThenApply$MonoThenApplyManager$SecondSubscriber.onNext(MonoThenApply.java:201) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:314) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:108) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:368) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:892) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.MonoReduce$ReduceSubscriber.onComplete(MonoReduce.java:149) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onComplete(FluxSubscribeOn.java:160) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.drain(NettyChannelHandler.java:696) ~[reactor-netty-0.5.1.RELEASE.jar!/:na]
  	at reactor.ipc.netty.common.NettyChannelHandler$InboundSink.request(NettyChannelHandler.java:772) ~[reactor-netty-0.5.1.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:136) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:129) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.ipc.netty.common.NettyChannelHandler.subscribe(NettyChannelHandler.java:543) ~[reactor-netty-0.5.1.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:59) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.publisher.FluxSubscribeOn$SourceSubscribeTask.run(FluxSubscribeOn.java:231) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at reactor.core.scheduler.ExecutorScheduler$ExecutorTrackedRunnable.run(ExecutorScheduler.java:136) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
  	at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451) ~[netty-all-4.1.3.Final.jar!/:4.1.3.Final]
  	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) ~[netty-all-4.1.3.Final.jar!/:4.1.3.Final]
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401) ~[netty-all-4.1.3.Final.jar!/:4.1.3.Final]
  	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) ~[netty-all-4.1.3.Final.jar!/:4.1.3.Final]
  	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_05]

  2016-11-16 15:43:54.012  INFO 53028 --- [           main] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@28c97a5: startup date [Wed Nov 16 15:43:46 MST 2016]; root of context hierarchy
  2016-11-16 15:43:54.012  INFO 53028 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
  ➜  cf-demo git:(master) ✗
  ```

Am I missing something here or is this a bug?

Thanks!

**Comment by twoseat** [comment]
Thanks for the beautifully comprehensive report @zilkey! We'll look into it, but in the meantime you might want to update to the 2.0.2 release. I'm not saying it will fix the problem, but it's the first thing we're going to try!

**Comment by zilkey** [comment]
Thanks for looking into it @twoseat!  I upgraded to 2.0.2 and it still appears to have the same bug.

The build.gradle file in https://github.com/zilkey/cloud-foundry-api-events-bug now looks like this:

```groovy
repositories {
	mavenCentral()
	maven { url 'http://repo.spring.io/release' }
}

dependencies {
	compile('org.springframework.boot:spring-boot-starter')
	compile 'org.cloudfoundry:cloudfoundry-client-reactor:2.0.2.RELEASE'
	compile 'org.cloudfoundry:cloudfoundry-operations:2.0.2.RELEASE'
	compile 'io.projectreactor:reactor-core:3.0.2.RELEASE'
	compile 'io.projectreactor.ipc:reactor-netty:0.5.1.RELEASE'
	testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

**Comment by zilkey** [comment]
Here's a copy of the events json that causes it to fail:

https://github.com/zilkey/cloud-foundry-api-events-bug/blob/master/events-result.json

**Comment by twoseat** [comment]
Thanks again for the report @zilkey - it turned out we were making an ill-founded assumption about some of the data coming out of the app events interface. That's been fixed, and as soon as we get a clean build (we're having some issues with a CI machine at the moment so it may take a while) you should be able to pick the fix up in a build snapshot. Let me know if you see any problems with that!

**Comment by zilkey** [comment]
Thanks!  What's the best way to get notified when that's released?

**Comment by twoseat** [comment]
After some coughs and splutters in CI it's now passed, so you should be able to pick it up now.

**Comment by twoseat** [comment]
@zilkey A clarification - if you're after an actual release version (rather than a snapshot) we're aiming for a 2.0.3 in the week after Thanksgiving, subject to other issues coming in.
