### ISSUE TITLE
Pushing an unzipped directory no longer works as of v2.1.0

### ISSUE THREAD

**Issue by forbushbl** [cloudfoundry/cf-java-client#603]
I have a utility that manages applications deployed to Cloud Foundry. It has a method that creates an applications as follows:

```
    public void createApplication(Application application) {
        LOG.info("Pushing application with noStart: " + application.getName());
        PushApplicationRequest pushApplicationRequest = PushApplicationRequest.builder()
                .noStart(true)
                .name(application.getName())
                .application(Paths.get(application.getPackagePath()))
                .buildpack(application.getBuildpack())
                .instances(application.getInstances())
                .memory(application.getMemory())
                .noRoute(true)
                .command(application.getCommand())
                .healthCheckType(applicationHealthCheck)
                .build();
        cf.applications().push(pushApplicationRequest).block();
```

Now that I've upgraded to v2.1.0, I get the following stack trace whenever the `createApplication()` method is called where the path is a directory (not a .zip or a .jar). NOTE: In my example above, `application.getPackagePath()` returns a string.

Here is the output from my logs:
```
16:45:47.446 [main] INFO  o.l.c.c.c.ApplicationController - Pushing application with noStart: operations-websocket-proxy
16:45:47.589 [reactor-http-nio-1] ERROR r.i.netty.channel.ChannelOperations - [HttpClient] Error processing connection. Requesting close the channel
io.netty.handler.codec.http.multipart.HttpPostRequestEncoder$ErrorDataEncoderException: java.io.FileNotFoundException: /Users/forbushbl/Projects/operations-websocket-proxy (Is a directory)
	at reactor.ipc.netty.http.client.HttpClientFormEncoder.file(HttpClientFormEncoder.java:820)
	at org.cloudfoundry.reactor.client.v2.applications.ReactorApplicationsV2.lambda$null$22(ReactorApplicationsV2.java:193)
	at reactor.ipc.netty.http.client.HttpClientOperations$FluxSendForm._subscribe(HttpClientOperations.java:655)
	at reactor.ipc.netty.http.client.HttpClientOperations$FluxSendForm.subscribe(HttpClientOperations.java:632)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:38)
	at reactor.core.publisher.MonoThenMap$MonoThenApplyMain.onNext(MonoThenMap.java:132)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:124)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1613)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:180)
	at reactor.core.publisher.MonoThenMap$MonoThenApplyMain.onSubscribe(MonoThenMap.java:83)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:94)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:64)
	at reactor.core.publisher.MonoThenMap.subscribe(MonoThenMap.java:55)
	at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:465)
	at reactor.ipc.netty.http.client.HttpClientOperations.onHandlerStart(HttpClientOperations.java:415)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /Users/forbushbl/Projects/operations-websocket-proxy (Is a directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at io.netty.handler.codec.http.multipart.AbstractMemoryHttpData.setContent(AbstractMemoryHttpData.java:135)
	at io.netty.handler.codec.http.multipart.MixedFileUpload.setContent(MixedFileUpload.java:209)
	at reactor.ipc.netty.http.client.HttpClientFormEncoder.file(HttpClientFormEncoder.java:813)
	... 20 common frames omitted
```

However, this directory still exists and still contains the application that previously pushed successfully.

```
▶ ll /Users/forbushbl/Projects/operations-websocket-proxy
total 88
-rw-r--r--  1 forbushbl  LDS\Domain Users  11057 Nov  2 22:44 app.js
-rw-r--r--  1 forbushbl  LDS\Domain Users    102 Oct 25 12:54 base_manifest.yml
-rw-r--r--  1 forbushbl  LDS\Domain Users    290 Oct 25 12:54 manifest-aws-east.yml
-rw-r--r--  1 forbushbl  LDS\Domain Users    258 Oct 25 12:54 manifest-dev.yml
-rw-r--r--  1 forbushbl  LDS\Domain Users    266 Oct 25 12:54 manifest-dev1.yml
-rw-r--r--  1 forbushbl  LDS\Domain Users    243 Oct 25 12:54 manifest-production.yml
-rw-r--r--  1 forbushbl  LDS\Domain Users    251 Oct 25 12:54 manifest-rob.yml
-rw-r--r--  1 forbushbl  LDS\Domain Users    258 Oct 25 12:54 manifest-test.yml
-rw-r--r--  1 forbushbl  LDS\Domain Users    537 Oct 27 19:38 package.json
```

**Comment by kelapure** [comment]
@nebhale  Given that 2.3.0 already released... Is this bug pushed out to 2.4.0 ?

**Comment by nebhale** [comment]
Yep, we've been tackling a deeper networking issue for the last couple of days, but I believe that this will make it into the next release.
