### ISSUE TITLE
Protect against empty-strings being passed for organization (and space?)

### ISSUE THREAD

**Issue by kdvolder** [cloudfoundry/cf-java-client#678]
When we try and create a cloudfoundry 'Operations' with org and space name set to empty string. We get a rather nasty exception. I'm including the full stacktrace which pinpoints a call to Flux.single as the place of origin.

```
java.util.concurrent.ExecutionException: java.io.IOException: java.lang.IndexOutOfBoundsException: Source emitted more than one item
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFTarget.getServices(CFTarget.java:103)
	at org.springframework.ide.vscode.manifest.yaml.ManifestYamlCFServicesProvider.getHints(ManifestYamlCFServicesProvider.java:40)
	at org.springframework.ide.vscode.manifest.yaml.AbstractCFHintsProvider.call(AbstractCFHintsProvider.java:56)
	at org.springframework.ide.vscode.manifest.yaml.AbstractCFHintsProvider.call(AbstractCFHintsProvider.java:30)
	at org.springframework.ide.vscode.commons.yaml.schema.YTypeFactory.lambda$valuesFromHintProvider$7(YTypeFactory.java:747)
	at org.springframework.ide.vscode.commons.util.EnumValueParser.lambda$provider$1(EnumValueParser.java:90)
	at org.springframework.ide.vscode.commons.util.EnumValueParser.parse(EnumValueParser.java:57)
	at org.springframework.ide.vscode.commons.yaml.reconcile.SchemaBasedYamlASTReconciler.reconcile(SchemaBasedYamlASTReconciler.java:179)
	at org.springframework.ide.vscode.commons.yaml.reconcile.SchemaBasedYamlASTReconciler.reconcile(SchemaBasedYamlASTReconciler.java:166)
	at org.springframework.ide.vscode.commons.yaml.reconcile.SchemaBasedYamlASTReconciler.reconcile(SchemaBasedYamlASTReconciler.java:153)
	at org.springframework.ide.vscode.commons.yaml.reconcile.SchemaBasedYamlASTReconciler.reconcile(SchemaBasedYamlASTReconciler.java:166)
	at org.springframework.ide.vscode.commons.yaml.reconcile.SchemaBasedYamlASTReconciler.reconcile(SchemaBasedYamlASTReconciler.java:153)
	at org.springframework.ide.vscode.commons.yaml.reconcile.SchemaBasedYamlASTReconciler.reconcile(SchemaBasedYamlASTReconciler.java:94)
	at org.springframework.ide.vscode.commons.yaml.reconcile.YamlReconcileEngine.reconcile(YamlReconcileEngine.java:46)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleLanguageServer.lambda$validateWith$1(SimpleLanguageServer.java:216)
	at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:37)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:62)
	at reactor.core.publisher.MonoSubscribeOn$MonoSubscribeOnSubscriber.run(MonoSubscribeOn.java:84)
	at reactor.core.scheduler.SingleScheduler$SingleWorker$SingleWorkerTask.run(SingleScheduler.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: java.lang.IndexOutOfBoundsException: Source emitted more than one item
	at org.springframework.ide.vscode.commons.cloudfoundry.client.v2.ReactorUtils.get(ReactorUtils.java:90)
	at org.springframework.ide.vscode.commons.cloudfoundry.client.v2.DefaultClientRequestsV2.getServices(DefaultClientRequestsV2.java:82)
	at org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFTarget$1.lambda$load$0(CFTarget.java:56)
	at org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFCallableContext.checkConnection(CFCallableContext.java:39)
	at org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFTarget.runAndCheckForFailure(CFTarget.java:77)
	at org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFTarget$1.load(CFTarget.java:56)
	at org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFTarget$1.load(CFTarget.java:49)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	... 29 more
Caused by: java.lang.IndexOutOfBoundsException: Source emitted more than one item
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:120)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:658)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:538)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:1057)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:93)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:56)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:382)
	at reactor.core.publisher.MonoFlatMap$FlattenSubscriber$InnerSubscriber.onNext(MonoFlatMap.java:191)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:355)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:584)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:213)
	at reactor.core.publisher.FluxBuffer$BufferExactSubscriber.onComplete(FluxBuffer.java:176)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:196)
	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:93)
	at reactor.core.publisher.FluxBuffer.subscribe(FluxBuffer.java:71)
	at reactor.core.publisher.FluxFlattenIterable.subscribe(FluxFlattenIterable.java:98)
	at reactor.core.publisher.MonoFlatMap$FlattenSubscriber.onNext(MonoFlatMap.java:154)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:166)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:78)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.MonoFlatMap$FlattenSubscriber$InnerSubscriber.onNext(MonoFlatMap.java:191)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:124)
	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:312)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:112)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:402)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:990)
	at reactor.core.publisher.MonoReduceSeed$ReduceSubscriber.onComplete(MonoReduceSeed.java:146)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
	at reactor.ipc.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:315)
	at reactor.ipc.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:427)
	at reactor.ipc.netty.channel.ChannelOperations.onHandlerTerminate(ChannelOperations.java:499)
	at reactor.ipc.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:469)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:271)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1069)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	... 1 more
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoSingle] :
	reactor.core.publisher.Flux.single(Flux.java:5105)
	org.cloudfoundry.operations._DefaultCloudFoundryOperations.getOrganization(_DefaultCloudFoundryOperations.java:231)
	org.cloudfoundry.operations._DefaultCloudFoundryOperations.lambda$getOrganizationId$0(_DefaultCloudFoundryOperations.java:175)
	java.util.Optional.map(Optional.java:215)
	org.cloudfoundry.operations._DefaultCloudFoundryOperations.getOrganizationId(_DefaultCloudFoundryOperations.java:175)
	org.cloudfoundry.operations.DefaultCloudFoundryOperations.access$2101(DefaultCloudFoundryOperations.java:30)
	org.cloudfoundry.operations.DefaultCloudFoundryOperations$InitShim.getOrganizationId(DefaultCloudFoundryOperations.java:268)
	org.cloudfoundry.operations.DefaultCloudFoundryOperations.getOrganizationId(DefaultCloudFoundryOperations.java:532)
	org.cloudfoundry.operations._DefaultCloudFoundryOperations.lambda$getSpaceId$2(_DefaultCloudFoundryOperations.java:203)
	java.util.Optional.map(Optional.java:215)
	org.cloudfoundry.operations._DefaultCloudFoundryOperations.getSpaceId(_DefaultCloudFoundryOperations.java:203)
	org.cloudfoundry.operations.DefaultCloudFoundryOperations.access$2301(DefaultCloudFoundryOperations.java:30)
	org.cloudfoundry.operations.DefaultCloudFoundryOperations$InitShim.getSpaceId(DefaultCloudFoundryOperations.java:292)
	org.cloudfoundry.operations.DefaultCloudFoundryOperations.getSpaceId(DefaultCloudFoundryOperations.java:570)
	org.cloudfoundry.operations._DefaultCloudFoundryOperations.applications(_DefaultCloudFoundryOperations.java:77)
	org.cloudfoundry.operations.DefaultCloudFoundryOperations.access$801(DefaultCloudFoundryOperations.java:30)
	org.cloudfoundry.operations.DefaultCloudFoundryOperations$InitShim.applications(DefaultCloudFoundryOperations.java:112)
	org.cloudfoundry.operations.DefaultCloudFoundryOperations.<init>(DefaultCloudFoundryOperations.java:66)
	org.cloudfoundry.operations.DefaultCloudFoundryOperations.<init>(DefaultCloudFoundryOperations.java:30)
	org.cloudfoundry.operations.DefaultCloudFoundryOperations$Builder.build(DefaultCloudFoundryOperations.java:850)
	org.springframework.ide.vscode.commons.cloudfoundry.client.v2.DefaultClientRequestsV2.<init>(DefaultClientRequestsV2.java:60)
	org.springframework.ide.vscode.commons.cloudfoundry.client.v2.DefaultCloudFoundryClientFactoryV2.getClient(DefaultCloudFoundryClientFactoryV2.java:41)
	org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFTargetCache.create(CFTargetCache.java:95)
	org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFTargetCache$1.load(CFTargetCache.java:48)
	org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFTargetCache$1.load(CFTargetCache.java:44)
	com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFTargetCache.doGetOrCreate(CFTargetCache.java:74)
	org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFTargetCache.lambda$getOrCreate$0(CFTargetCache.java:64)
	org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFCallableContext.checkConnection(CFCallableContext.java:39)
	org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFTargetCache.getOrCreate(CFTargetCache.java:64)
	org.springframework.ide.vscode.manifest.yaml.AbstractCFHintsProvider.call(AbstractCFHintsProvider.java:52)
	org.springframework.ide.vscode.manifest.yaml.AbstractCFHintsProvider.call(AbstractCFHintsProvider.java:30)
	org.springframework.ide.vscode.commons.yaml.schema.YTypeFactory.lambda$valuesFromHintProvider$7(YTypeFactory.java:747)
	org.springframework.ide.vscode.commons.util.EnumValueParser.lambda$provider$1(EnumValueParser.java:90)
	org.springframework.ide.vscode.commons.util.EnumValueParser.parse(EnumValueParser.java:57)
	org.springframework.ide.vscode.commons.yaml.reconcile.SchemaBasedYamlASTReconciler.reconcile(SchemaBasedYamlASTReconciler.java:179)
	org.springframework.ide.vscode.commons.yaml.reconcile.SchemaBasedYamlASTReconciler.reconcile(SchemaBasedYamlASTReconciler.java:166)
	org.springframework.ide.vscode.commons.yaml.reconcile.SchemaBasedYamlASTReconciler.reconcile(SchemaBasedYamlASTReconciler.java:153)
	org.springframework.ide.vscode.commons.yaml.reconcile.SchemaBasedYamlASTReconciler.reconcile(SchemaBasedYamlASTReconciler.java:166)
	org.springframework.ide.vscode.commons.yaml.reconcile.SchemaBasedYamlASTReconciler.reconcile(SchemaBasedYamlASTReconciler.java:153)
	org.springframework.ide.vscode.commons.yaml.reconcile.SchemaBasedYamlASTReconciler.reconcile(SchemaBasedYamlASTReconciler.java:94)
	org.springframework.ide.vscode.commons.yaml.reconcile.YamlReconcileEngine.reconcile(YamlReconcileEngine.java:46)
	org.springframework.ide.vscode.commons.languageserver.util.SimpleLanguageServer.lambda$validateWith$1(SimpleLanguageServer.java:216)
	reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:37)
	reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:62)
	reactor.core.publisher.MonoSubscribeOn$MonoSubscribeOnSubscriber.run(MonoSubscribeOn.java:84)
	reactor.core.scheduler.SingleScheduler$SingleWorker$SingleWorkerTask.run(SingleScheduler.java:247)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
Composition chain until failing Operator :
	|_	Flux.single(_DefaultCloudFoundryOperations.java:231)
```

**Comment by nebhale** [comment]
For whomever works this, the plan would be to treat an empty string the same way we treat `null` in the `DefaultOperations` builder.  It should result in a `Mono.error()`.
