### ISSUE TITLE
Push app using path Directory

### ISSUE THREAD

**Issue by ngocvanho** [cloudfoundry/cf-java-client#723]
Hi All,
I was pushed application with path is a Directory but when i was executed display error: 
`Exception in thread "main" java.lang.UnsupportedOperationException`
Could you let me know cloudfoundry-operation  version 2.8.0.RELEASE can push app with path is a Directory? 
Below my code:

```
pushAppRequest = PushApplicationRequest.builder()
                    .application(new ClassPathResource("/helloworld").getFile().toPath())
                    .name("helloworld")
                    .buildpack("staticfile_buildpack')
                    .instances(1)
                    .memory(64)
                    .stagingTimeout(Duration.ofMinutes(2))
                    .startupTimeout(Duration.ofMinutes(2)).build();
this.cloudFoundryOperations.applications().push(pushAppRequest)
```

Thanks,
Van

**Comment by nebhale** [comment]
The operations layer has supported pushing applications for quite some time.  So long ago in fact, that I don't know when we added support (Somewhere in 2.0.0 milestones).  Out [integration tests](https://github.com/cloudfoundry/cf-java-client/blob/master/integration-test/src/test/java/org/cloudfoundry/operations/ApplicationsTest.java#L190) ensure that this works during each test run.  Your full stack trace will tell you which bit of code actually generated the exception.

**Comment by ngocvanho** [comment]
Thanks your response. I was seen and apply code follow to integration tests but when i was executed display error below:

Exception in thread "main" java.lang.UnsupportedOperationException
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:192)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at org.cloudfoundry.util.FileUtils.getUnixMode(FileUtils.java:239)
	at org.cloudfoundry.util.FileUtils.permissions(FileUtils.java:166)
	at org.cloudfoundry.util.ResourceMatchingUtils.lambda$getArtifactMetadataFromDirectory$5(ResourceMatchingUtils.java:74)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.tryOnNext(FluxFilter.java:125)
	at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.fastPath(FluxIterable.java:503)
	at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.request(FluxIterable.java:403)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.request(FluxFilter.java:176)
	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:166)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onSubscribe(MonoCollect.java:99)
	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onSubscribe(FluxFilter.java:80)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:93)
	at reactor.core.publisher.FluxStream.subscribe(FluxStream.java:60)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:59)
	at reactor.core.publisher.FluxFilter.subscribe(FluxFilter.java:56)
	at reactor.core.publisher.FluxMap.subscribe(FluxMap.java:67)
	at reactor.core.publisher.MonoCollect.subscribe(MonoCollect.java:66)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:46)
	at reactor.core.publisher.MonoCollectList.subscribe(MonoCollectList.java:58)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:78)
	at reactor.core.publisher.MonoSubscribeOn$MonoSubscribeOnSubscriber.run(MonoSubscribeOn.java:84)
	at reactor.core.scheduler.ElasticScheduler$CachedWorker$CachedTask.run(ElasticScheduler.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoThenMap] :
	reactor.core.publisher.Mono.checkpoint(Mono.java:1286)
	org.cloudfoundry.operations.applications.DefaultApplications.push(DefaultApplications.java:328)
	org.cloudfoundry.cf.operation.sample.services.ClientOperationServiceImpl.createApplication(ClientOperationServiceImpl.java:59)
	org.cloudfoundry.cf.operation.sample.App.main(App.java:38)
Error has been observed by the following operator(s):
	|_	Mono.checkpoint(DefaultApplications.java:328)

	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1189)
		at org.cloudfoundry.cf.operation.sample.services.ClientOperationServiceImpl.createApplication(ClientOperationServiceImpl.java:63)
		at org.cloudfoundry.cf.operation.sample.App.main(App.java:38)


Please help me if you know this problems.

Thanks,
Van

**Comment by nebhale** [comment]
Yep, we do no testing on Windows at all.  I'll take a look at what we can do to support this.

**Comment by stipx** [comment]
Had the same issue. My workaround was to temporarily zip the app contents and use that one as "application".

**Comment by nebhale** [comment]
@ngocvanho or @stipx The next snapshot should account for non-POSIX filesystems.  If you could give this snapshot a test and let me know if it works for you, that'd be great.

**Comment by stipx** [comment]
Seems to work with 2.9.0.BUILD-SNAPSHOT

**Comment by nebhale** [comment]
Great to hear.
