### ISSUE TITLE
Failed to locate envelope.proto in 

### ISSUE THREAD

**Issue by shahprincea** [cloudfoundry/cf-java-client#747]
HI Guys I am just getting started with master branch and i clone it and build using `mvn clean package` and I see following. 

Not sure how to get those proto files.... 

```
[ERROR] Failed to execute goal com.squareup.wire:wire-maven-plugin:2.2.0:generate-sources (default) on project cloudfoundry-client: Wire Plugin: Failure compiling proto sources. Failed to locate envelope.proto in [/Users/princeshah/Codebase/cf-java-client-2-xxx/cloudfoundry-client/../vendor/dropsonde-protocol/events] -> [Help 1]
```

**Comment by nebhale** [comment]
You've missed the step in the [documentation](https://github.com/cloudfoundry/cf-java-client#development) that initializes the submodule.

**Comment by shahprincea** [comment]
You are RIGHT !!! :) 

Did that and now ran in to proxy issues any suggestion where to put proxy ?? 
Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.5.0/apache-maven-3.5.0-bin.zip

Exception in thread "main" java.net.UnknownHostException: repo1.maven.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:73)
        at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:60)
        at org.apache.maven.wrapper.Installer.createDist(Installer.java:64)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)

**Comment by nebhale** [comment]
Seems like setting the `MAVEN_OPTS` environment variable with [standard Java proxy system properties](http://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html) will work.

**Comment by shahprincea** [comment]
Figured it out need to set proxy using "export MAVEN_OPTS='
'"
