### ISSUE TITLE
Binding a second tcp-routes throws `java.lang.IndexOutOfBoundsException: Source emitted more than one item`

### ISSUE THREAD

**Issue by kdvolder** [cloudfoundry/cf-java-client#770]
I think you know how to run my sample code by now. It's here:

https://github.com/kdvolder/cf-java-client-sample-v2/tree/4bd7b823cfc3c91955f6618be45f0ca71ff51d73

Output:

```
Starting...
[main] WARN cloudfoundry-client.trust - Trusting SSL Certificate for api.local2.pcfdev.io:443
[main] DEBUG cloudfoundry-client.trust - Trusted SSL Certificate for api.local2.pcfdev.io:443
Using PASSWORD token for auth
[main] DEBUG cloudfoundry-client.operations - START  Push Manifest
[main] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/organizations?q=name:pcfdev-org&page=1
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.token - Negotiating using token provider
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/info
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/info (30 ms)
[cloudfoundry-client-nio-7] WARN cloudfoundry-client.trust - Trusting SSL Certificate for login.local2.pcfdev.io:443
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.trust - Trusted SSL Certificate for login.local2.pcfdev.io:443
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.request - POST   https://login.local2.pcfdev.io:443/oauth/token
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.response - 200    https://login.local2.pcfdev.io:443/oauth/token (159 ms)
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.token - Refresh Token: 75c04a829e6d49c5b70a9a189bab14c5-r
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.token - Access Token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImtleS0xIiwidHlwIjoiSldUIn0.eyJqdGkiOiJkMzkzN2ZiZDVmOTY0NTNhODI5YTNiY2QxM2YwOTIxZSIsInN1YiI6IjI1MWIyNGI1LTZlYTQtNDc0Ny05MzAwLTEyNWQzZGI0ZDdhMCIsInNjb3BlIjpbIm9wZW5pZCIsInJvdXRpbmcucm91dGVyX2dyb3Vwcy53cml0ZSIsInNjaW0ucmVhZCIsImNsb3VkX2NvbnRyb2xsZXIuYWRtaW4iLCJ1YWEudXNlciIsInJvdXRpbmcucm91dGVyX2dyb3Vwcy5yZWFkIiwiY2xvdWRfY29udHJvbGxlci5yZWFkIiwicGFzc3dvcmQud3JpdGUiLCJjbG91ZF9jb250cm9sbGVyLndyaXRlIiwiZG9wcGxlci5maXJlaG9zZSIsInNjaW0ud3JpdGUiXSwiY2xpZW50X2lkIjoiY2YiLCJjaWQiOiJjZiIsImF6cCI6ImNmIiwiZ3JhbnRfdHlwZSI6InBhc3N3b3JkIiwidXNlcl9pZCI6IjI1MWIyNGI1LTZlYTQtNDc0Ny05MzAwLTEyNWQzZGI0ZDdhMCIsIm9yaWdpbiI6InVhYSIsInVzZXJfbmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbiIsImF1dGhfdGltZSI6MTQ5NzYzNTc0MiwicmV2X3NpZyI6Ijc0YTExMDc1IiwiaWF0IjoxNDk3NjM1NzQyLCJleHAiOjE0OTc2MzYzNDIsImlzcyI6Imh0dHBzOi8vdWFhLmxvY2FsMi5wY2ZkZXYuaW8vb2F1dGgvdG9rZW4iLCJ6aWQiOiJ1YWEiLCJhdWQiOlsic2NpbSIsImNsb3VkX2NvbnRyb2xsZXIiLCJwYXNzd29yZCIsImNmIiwidWFhIiwib3BlbmlkIiwiZG9wcGxlciIsInJvdXRpbmcucm91dGVyX2dyb3VwcyJdfQ.M0MDoEL7nF39_RxiETV-LwQ1GRmehg0gnBfDjmepqhMvptlTABfk3vG-T2ZrG76CABhl6zJrzI2uVHcSOo_I7p5NHJSowZTcNeekvV2se9eHn9FEVdFxJcx_VOSARuZWDovBjxAtzdO1s-5p4iD5Gr33PohZ2NLLn93FP7MUaGA
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.token - Access Token Issued At:  2017-06-16T17:55:42 UTC
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.token - Access Token Expires At: 2017-06-16T18:05:42 UTC
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/organizations?q=name:pcfdev-org&page=1 (318 ms)
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/spaces?q=name:pcfdev-space&q=organization_guid:532e5a31-2b96-4812-88ff-14fca73596ab&page=1
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/spaces?q=name:pcfdev-space&q=organization_guid:532e5a31-2b96-4812-88ff-14fca73596ab&page=1 (46 ms)
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/spaces/984c86dc-533c-4fe2-be7c-3acf61cfd77e
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/spaces/984c86dc-533c-4fe2-be7c-3acf61cfd77e (43 ms)
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/organizations/532e5a31-2b96-4812-88ff-14fca73596ab/private_domains?page=1
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/shared_domains?page=1
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/organizations/532e5a31-2b96-4812-88ff-14fca73596ab/private_domains?page=1 (40 ms)
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/shared_domains?page=1 (152 ms)
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/spaces/984c86dc-533c-4fe2-be7c-3acf61cfd77e/apps?q=name:test-static-aaasd&page=1
[elastic-2] DEBUG cloudfoundry-client.request - PUT    https://api.local2.pcfdev.io:443/v2/resource_match
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/spaces/984c86dc-533c-4fe2-be7c-3acf61cfd77e/apps?q=name:test-static-aaasd&page=1 (33 ms)
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.request - POST   https://api.local2.pcfdev.io:443/v2/apps
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/resource_match (62 ms)
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.resource-matching - 0 resources matched totaling 0 B
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.response - 201    https://api.local2.pcfdev.io:443/v2/apps (54 ms)
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.request - POST   https://api.local2.pcfdev.io:443/v2/routes?generate_port=true
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.response - 201    https://api.local2.pcfdev.io:443/v2/routes?generate_port=true (134 ms)
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.request - PUT    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/routes/7fada7a2-5c8b-45fb-b73c-fe757a30897c
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.response - 201    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/routes/7fada7a2-5c8b-45fb-b73c-fe757a30897c (66 ms)
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.request - PUT    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/bits?async=true
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.response - 201    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/bits?async=true (40 ms)
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/jobs/971ec9ea-7405-43b8-8bc2-aec6b3857882
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/jobs/971ec9ea-7405-43b8-8bc2-aec6b3857882 (22 ms)
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.delay - Delaying 1 second
[parallel-1] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/jobs/971ec9ea-7405-43b8-8bc2-aec6b3857882
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/jobs/971ec9ea-7405-43b8-8bc2-aec6b3857882 (28 ms)
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.delay - Delaying 2 seconds
[parallel-2] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/jobs/971ec9ea-7405-43b8-8bc2-aec6b3857882
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/jobs/971ec9ea-7405-43b8-8bc2-aec6b3857882 (27 ms)
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.request - PUT    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.response - 201    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a (69 ms)
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.request - PUT    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.response - 201    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a (144 ms)
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a (41 ms)
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.delay - Delaying 1 second
[parallel-3] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a (77 ms)
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.delay - Delaying 2 seconds
[parallel-4] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a (45 ms)
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.delay - Delaying 4 seconds
[parallel-5] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a (91 ms)
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/instances
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/instances (27 ms)
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.delay - Delaying 1 second
[parallel-6] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/instances
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/instances (56 ms)
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.operations - FINISH Push Manifest (onComplete/12.9 s)
[main] DEBUG cloudfoundry-client.operations - START  Get Application
[main] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/spaces/984c86dc-533c-4fe2-be7c-3acf61cfd77e/apps?q=name:test-static-aaasd&page=1
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/spaces/984c86dc-533c-4fe2-be7c-3acf61cfd77e/apps?q=name:test-static-aaasd&page=1 (52 ms)
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/stats
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/summary
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/instances
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/stats (57 ms)
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/summary (66 ms)
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/apps/935ce881-18bb-4311-b5dd-0ae98ca78f1a/instances (73 ms)
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/stacks/e6072307-54f7-4cdd-ba63-cd7849eb816f
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/stacks/e6072307-54f7-4cdd-ba63-cd7849eb816f (27 ms)
app deployed at: [tcp.local2.pcfdev.io]
Binding a tcp route...[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.operations - FINISH Get Application (onComplete/196 ms)

[main] DEBUG cloudfoundry-client.operations - START  Map Route
[main] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/organizations/532e5a31-2b96-4812-88ff-14fca73596ab/private_domains?q=name:tcp.local2.pcfdev.io&page=1
[main] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/spaces/984c86dc-533c-4fe2-be7c-3acf61cfd77e/apps?q=name:test-static-aaasd&page=1
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/organizations/532e5a31-2b96-4812-88ff-14fca73596ab/private_domains?q=name:tcp.local2.pcfdev.io&page=1 (44 ms)
[cloudfoundry-client-nio-7] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/shared_domains?q=name:tcp.local2.pcfdev.io&page=1
[cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/spaces/984c86dc-533c-4fe2-be7c-3acf61cfd77e/apps?q=name:test-static-aaasd&page=1 (57 ms)
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/shared_domains?q=name:tcp.local2.pcfdev.io&page=1 (58 ms)
[cloudfoundry-client-nio-3] DEBUG cloudfoundry-client.request - GET    https://api.local2.pcfdev.io:443/v2/routes?q=domain_guid:d327cf72-1606-49c4-aa86-072de6fbc8af&page=1
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.response - 200    https://api.local2.pcfdev.io:443/v2/routes?q=domain_guid:d327cf72-1606-49c4-aa86-072de6fbc8af&page=1 (27 ms)
[cloudfoundry-client-nio-5] DEBUG cloudfoundry-client.operations - FINISH Map Route (onError/148 ms)
Exception in thread "main" java.lang.IndexOutOfBoundsException: Source emitted more than one item
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:128)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:96)
	at reactor.core.publisher.FluxFilter$FilterConditionalSubscriber.onNext(FluxFilter.java:214)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:612)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:491)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:900)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:89)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:54)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:384)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:235)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:385)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:616)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:241)
	at reactor.core.publisher.FluxBuffer$BufferExactSubscriber.onComplete(FluxBuffer.java:177)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:183)
	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:79)
	at reactor.core.publisher.FluxBuffer.subscribe(FluxBuffer.java:72)
	at reactor.core.publisher.FluxFlattenIterable.subscribe(FluxFlattenIterable.java:104)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:183)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:373)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:173)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:235)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:207)
	at reactor.ipc.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:322)
	at reactor.ipc.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:316)
	at reactor.ipc.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:581)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at reactor.ipc.netty.http.HttpOperations.lambda$static$3(HttpOperations.java:261)
	at reactor.ipc.netty.ReactorNetty$ExtractorHandler.channelRead(ReactorNetty.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1240)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1041)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoDoFinallyFuseable] :
	reactor.core.publisher.Mono.checkpoint(Mono.java:1400)
	org.cloudfoundry.operations.routes.DefaultRoutes.map(DefaultRoutes.java:183)
	com.github.kdvolder.cfv2sample.CFV2SampleMain.pushAppAndBindTcpRoute(CFV2SampleMain.java:112)
	com.github.kdvolder.cfv2sample.CFV2SampleMain.main(CFV2SampleMain.java:87)
Error has been observed by the following operator(s):
	|_	Mono.checkpoint(DefaultRoutes.java:183)

	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:86)
		at reactor.core.publisher.Mono.block(Mono.java:1301)
		at com.github.kdvolder.cfv2sample.CFV2SampleMain.pushAppAndBindTcpRoute(CFV2SampleMain.java:117)
		at com.github.kdvolder.cfv2sample.CFV2SampleMain.main(CFV2SampleMain.java:87)
```

**Comment by kdvolder** [comment]
The sample pushes an app with a random tcp route. Then it tries to bind an additional tcp-route with a fixed port. This fails (even though I think it should succeed).

**Comment by kdvolder** [comment]
Note this isn't as important an issue for us to get fixed. I accidentally ran into it mucking around with my 'test app' but I think its highly unlikely we'd ever do something like this from our production code.

**Comment by kdvolder** [comment]
Note: did a quick test where the second route is bound with a fixed port and that seems to work fine. So this bug is specific to `randomPort(true)` scenario.
