### ISSUE TITLE
SSLException bad_record_mac while calling PUT v2/resource_match

### ISSUE THREAD

**Issue by tun-chang-ge** [cloudfoundry/cf-java-client#797]
We are using the following version but we can reproduce with other versions as well.
1. cloudfoundry-client-reactor 2.10.0.RELEASE
2. cloudfoundry-operations 2.10.0.RELEASE
3. reactor-core 3.0.7.RELEASE
4. reactor-netty 0.6.2.RELEASE
5. JDK 1.8.0_65
6. Java buildpack version 3.13

Symptom: We are using the CF Java client to do the equivalent of "cf push".  That is, we are calling `Applications.push`.  If the jar we are pushing has about 80 or more entries, the call to `PUT /v2/resource_match` gets into `io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: bad_record_mac exception`.

Severity: This is a blocker for us since we cannot push a Java application of decent size.

Exception stack:
```
2017-08-15T10:19:33.420-07:00	[None]	[None]	[ERROR]	[reactor-http-nio-7]	reactor.ipc.netty.channel.ChannelOperations	[HttpClient] Error processing connection. Requesting close the channel
******* STACK TRACE *******io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: bad_record_mac
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[netty-codec-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[netty-codec-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:255) [netty-handler-proxy-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:252) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: javax.net.ssl.SSLException: Received fatal alert: bad_record_mac
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.8.0_65]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[na:1.8.0_65]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[na:1.8.0_65]
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[na:1.8.0_65]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[na:1.8.0_65]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[na:1.8.0_65]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_65]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_65]
	at io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler.java:223) ~[netty-handler-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1117) ~[netty-handler-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1039) ~[netty-handler-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[netty-codec-4.1.8.Final.jar:4.1.8.Final]
	... 24 common frames omitted
```

**Comment by nebhale** [comment]
Have you reproduced this with the [latest versions](https://github.com/cloudfoundry/cf-java-client#dependencies) of all dependencies, specifically the latest version of `reactor-netty` which brings in the latest supported version of Netty?

/cc @smaldini

**Comment by tun-chang-ge** [comment]
@nebhale 

Yes, I was able to reproduce with the latest versions.
1. cloudfoundry-client-reactor 2.16.0.RELEASE
2. cloudfoundry-operations 2.16.0.RELEASE
3. reactor-core 3.0.7.RELEASE
4. reactor-netty 0.6.4.RELEASE

**Comment by nebhale** [comment]
@smaldini or @violetagg any chance this is related to your recent changes?

**Comment by tun-chang-ge** [comment]
@nebhale @smaldini @violetagg

If there is any workaround or if there is anything you want me to try, let me know.  We upgraded our CF version recently.  Along with that we were forced to upgrade CF Java client version to 2.x.x.  We were using the Java client version 1.1.1 before and didn't have this issue.  Thanks for your help.

**Comment by violetagg** [comment]
Hello,

Is it possible to try with the current Reactor Netty 0.6.5 Snapshot version available here [1]?

Thanks,
Violeta

[1] http://repo.spring.io/libs-snapshot/io/projectreactor/ipc/reactor-netty/0.6.5.BUILD-SNAPSHOT/

**Comment by violetagg** [comment]
@tun-chang-ge Also please specify the JDK version.

**Comment by tun-chang-ge** [comment]
@violetagg 

Locally jdk 1.8.0_65.  In CloudFoundry, it's open jdk 1.8.

**Comment by tun-chang-ge** [comment]
@violetagg 

I can still reproduce it.

1. cloudfoundry-client-reactor 2.16.0.RELEASE
2. cloudfoundry-operations 2.16.0.RELEASE
3. reactor-core 3.0.7.RELEASE
4. reactor-netty 0.6.5.BUILD-SNAPSHOT

```
2017-08-15T12:26:27.835-07:00	[None]	[None]	[ERROR]	[reactor-http-nio-6]	reactor.ipc.netty.channel.ChannelOperations	[HttpClient] Error processing connection. Requesting close the channel
******* STACK TRACE *******io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: bad_record_mac
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[netty-codec-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[netty-codec-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:255) [netty-handler-proxy-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:255) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: javax.net.ssl.SSLException: Received fatal alert: bad_record_mac
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.8.0_65]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[na:1.8.0_65]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[na:1.8.0_65]
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[na:1.8.0_65]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[na:1.8.0_65]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[na:1.8.0_65]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_65]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_65]
	at io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler.java:222) ~[netty-handler-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1119) ~[netty-handler-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1041) ~[netty-handler-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[netty-codec-4.1.9.Final.jar:4.1.9.Final]
	... 24 common frames omitted
```

**Comment by tun-chang-ge** [comment]
[ssl-bad-record-mac.txt](https://github.com/cloudfoundry/cf-java-client/files/1226607/ssl-bad-record-mac.txt)

@violetagg 

Thanks for your help and sorry for the delay.  I've attached the log you requested.

**Comment by tun-chang-ge** [comment]
@violetagg Did the SSL debug log help?  Please let me know if you need any additional info.  Thanks.

**Comment by tun-chang-ge** [comment]
@nebhale @smaldini @violetagg Are you able to reproduce this issue?  Let me know if you need a reproducible jar.

**Comment by violetagg** [comment]
@tun-chang-ge yes if you can provide some simple reproducible scenario it will definitely speed up the investigation

**Comment by tun-chang-ge** [comment]
[bad_record_mac.txt](https://github.com/cloudfoundry/cf-java-client/files/1229686/bad_record_mac.txt)
@nebhale @smaldini @violetagg I've attached the reproducible jar.  Rename the attached .txt file to .jar and try pushing.

**Comment by violetagg** [comment]
@tun-chang-ge I'm not able to reproduce this issue with the provided jar and using PCF. If I create a branch with configurations for Reactor Netty, would you be able to build it and use it to reproduce the issue on you side?

**Comment by tun-chang-ge** [comment]
@violetagg 

That's interesting finding.  Let me get the version of CF we are running.  And yes, we can build the branch and reproduce the issue.  Thanks.

**Comment by tun-chang-ge** [comment]
@violetagg

We are running V253 and we are not running PCF

**Comment by violetagg** [comment]
@tun-chang-ge 

Can you try to reproduce the issue with CF Java Client `2.17.0.BUILD-SNAPSHOT`?
We added the following 2 configuration options to `DefaultConnectionContext`:
- `sslCloseNotifyFlushTimeout`: this is the timeout for flushing the `close_notify` that was triggered by closing the channel. The default value for this timeout is 3000ms 
- `sslCloseNotifyReadTimeout`: this is the timeout for receiving the response for the `close_notify` that was triggered by closing the channel. The default value for this timeout is 0ms.

So your `DefaultConnectionContext ` should look like this:
```
DefaultConnectionContext.builder()
        .apiHost(apiHost)
        .sslCloseNotifyFlushTimeout(Duration)
        .sslCloseNotifyReadTimeout(Duration)
        .<other configurations if it is needed>
        .build();
```

Thanks,
Violeta

**Comment by tun-chang-ge** [comment]
@violetagg

Thank you.  We'll try and let you know the results.

**Comment by nebhale** [comment]
@tun-chang-ge I’ve sent you a meeting request so that @violetagg and I can work through this with you this morning.  If you’re available, please accept that request and we’ll make sure to be there.

**Comment by tun-chang-ge** [comment]
@nebhale @violetagg 

Yes, I am available to meet.  I haven't received the meeting invite though.  Is it because this account is opened with my corporate email address?  I am new to this so please bear with me.

**Comment by tun-chang-ge** [comment]
@violetagg Please try to reproduce again with this attachment.  And our java buildpack version is 3.13.

[bad_record_mac_issue_797.txt](https://github.com/cloudfoundry/cf-java-client/files/1235093/bad_record_mac_issue_797.txt)

**Comment by violetagg** [comment]
@tun-chang-ge I tried with java-buildpack both v4.4 and v3.15 in PCF the application binaries were uploaded successfully, but the application failed to start because of
```
   2017-08-18T21:32:36.93+0300 [APP/PROC/WEB/0] OUT Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.amqp.rabbit.connection.ConnectionFactory org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration.connectionFactory; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rabbitmqConnectionFactory' defined in class path resource [com/ge/predix/analytics/javabasedanalytic/JavaBasedAnalyticApplication$CloudConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.amqp.rabbit.connection.ConnectionFactory]: Factory method 'rabbitmqConnectionFactory' threw exception; nested exception is org.springframework.cloud.CloudException: No unique service matching interface org.springframework.amqp.rabbit.connection.ConnectionFactory found. Expected 1, found 0
```
Most probably I'm missing some service, however this is not related to the issue.

**Comment by tun-chang-ge** [comment]
@violetagg 

Yes, the error we are getting happens much earlier.  You cannot reproduce then.  So seems like CF version is a part of the issue.  The combination of CF version and CF Java client version is needed to reproduce the error, I guess.  Thanks for trying.  We'll try out your snapshot version when we get a chance.

**Comment by nebhale** [comment]
Well, might not be so much the version of CF as the instance of CF.  We’ve seen before in practice that Predix has a network device somewhere in the request chain that isn’t quite compliant with the HTTP spec.  If you’re up for it, @violetagg would like to use the Zoom meeting to pair with you and do the diagnosis from your machine to Predix and determine what the problem is as you reproduce it.

**Comment by tun-chang-ge** [comment]
@nebhale @violetagg @smaldini 

Just to give an update.  We are testing a solution that is working for us so far.  Here is what we did.

1. Bypass the resource_match API call when pushing the app.
2. Reactor Netty 0.6.5 Snapshot reactor-netty-0.6.5.BUILD-20170802.185359-2.jar to workaround Client Closes Connection Before Entire Payload Sent #134 issue.

We also tried reactor-netty-0.6.5.BUILD-20170817.174457-3.jar that has the sslCloseNotifyFlushTimeout and sslCloseNotifyReadTimeout support by @violetagg .  But with this version 3, uploading the payload is not working for us. 

We are going to test and use this workaround for the short term as we have the production degradation.  In a day or two, we'll pair with @violetagg to reproduce and diagnose the issue.

@violetagg Which time zone are you in?  When is usually the best time to reach you?

**Comment by nebhale** [comment]
I’m a bit concerned with the stamens that you’re bypassing the `resource_match` API when pushing the application.  There is no supported way to do this in any release or snapshot, so could you please expand on what you’ve done there?

**Comment by tun-chang-ge** [comment]
Hi @nebhale We took a fork of 2.10.0-RELEASE and made a code change to return empty list instead of making a call to `resource_match` API.

**Comment by nebhale** [comment]
Right, I’d consider that to be disqualifying in any testing that you’ve been doing if you are testing with that setup.  There have been [206 commits](https://github.com/cloudfoundry/cf-java-client/compare/v2.10.0.RELEASE...master) of all kinds since then, including changes to how the library uses `reactor-netty`.  In fact, `reactor-netty` and the Java Client have very tightly coupled version dependencies and must always be in sync with one another.  If you have not already done so, we’d like you to test with an unmodified version of the latest 2.17.0.BUILD-SNAPSHOT Java Client with an unmodified version of the latest 0.6.5.BUILD-SNAPSHOT from `reactor-netty`.

**Comment by tun-chang-ge** [comment]
@nebhale  We understand.  This is for very short term and this may not pass our tests either.  But we'll continue to work with you and team to get to a solution.

**Comment by nebhale** [comment]
@tun-chang-ge @violetagg is going on holiday this afternoon, but @smaldini and I will be available for the call.  I'll send you another appointment for tomorrow.

**Comment by tun-chang-ge** [comment]
Thank you @nebhale really appreciate your help

**Comment by tun-chang-ge** [comment]
@nebhale

@allen-chu-ge  from our team will connect with you on the Cloud Foundry Slack's #java-client channel.  He can pair with your team to troubleshoot this issue.  Thanks.

**Comment by tun-chang-ge** [comment]
@nebhale @smaldini @violetagg 

Thanks for helping me and @allen-chu-ge to troubleshoot this issue.  It's clear that the issue is with our application.  Probably, some dependencies or some other threads in our application.  Thanks for providing the Java client test app.  That really helps.  With that, we are going to continue troubleshooting our app.  If there is anything worth sharing when we find the cause, we'll do that.  In the mean time, we are going to close this issue.

**Comment by nebhale** [comment]
Copy that.  Thanks for the update.
