### ISSUE TITLE
NullPointerException in DropletResource by client v3 3.0.0.RELEASE

### ISSUE THREAD

**Issue by patsys** [cloudfoundry/cf-java-client#825]
I get a `NullPointerException` in `DropletResource` by `CopyDropletResponse` and by `ListDropletsResponse`  after Copy a Droplet. Probably because by the response
 in json the value is null by resources -> links -> package

Stacktrace:
```
2017-10-13 16:02:02.218 ERROR 17583 --- [ry-client-nio-3] cloudfoundry-client.response             : Can not construct instance of org.cloudfoundry.client.v3.droplets.DropletResource, problem: links value
 at [Source: [B@1ab39d2; line: 53, column: 5] (through reference chain: org.cloudfoundry.client.v3.droplets.ListDropletsResponse$Json["resources"]->java.util.ArrayList[0])
{
  "pagination": {
    "total_results": 1,
    "total_pages": 1,
    "first": {
      "href": "https://***/v3/droplets?app_guids=302ddab7-9737-40e4-8f81-4589715309a7&organization_guids=e399ec74-1c70-4122-8a9d-bcfe5090be98&page=1&per_page=50&space_guids=8ae8ff1c-af4c-490d-b78a-5e35a4b32c89"
    },
    "last": {
      "href": "https://***/v3/droplets?app_guids=302ddab7-9737-40e4-8f81-4589715309a7&organization_guids=e399ec74-1c70-4122-8a9d-bcfe5090be98&page=1&per_page=50&space_guids=8ae8ff1c-af4c-490d-b78a-5e35a4b32c89"
    },
    "next": null,
    "previous": null
  },
  "resources": [
    {
      "guid": "add07c98-6df7-4564-a8c4-a89131e12874",
      "state": "COPYING",
      "error": null,
      "lifecycle": {
        "type": "buildpack",
        "data": {

        }
      },
      "checksum": null,
      "buildpacks": [
        {
          "name": "https://github.com/cloudfoundry/buildpack-python.git",
          "detect_output": null
        }
      ],
      "stack": "cflinuxfs2",
      "image": null,
      "execution_metadata": "[PRIVATE DATA HIDDEN IN LISTS]",
      "process_types": {
        "redacted_message": "[PRIVATE DATA HIDDEN IN LISTS]"
      },
      "created_at": "2017-10-13T14:02:02Z",
      "updated_at": "2017-10-13T14:02:02Z",
      "links": {
        "self": {
          "href": "https://***/v3/droplets/add07c98-6df7-4564-a8c4-a89131e12874"
        },
        "package": null,
        "app": {
          "href": "https://***/v3/apps/302ddab7-9737-40e4-8f81-4589715309a7"
        },
        "assign_current_droplet": {
          "href": "https://***/v3/apps/302ddab7-9737-40e4-8f81-4589715309a7/relationships/current_droplet",
          "method": "PATCH"
        }
      }
    }
  ]
}
2017-10-13 16:02:02.246 ERROR 17583 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.cloudfoundry.reactor.util.JsonParsingException: Can not construct instance of org.cloudfoundry.client.v3.droplets.DropletResource, problem: links value
 at [Source: [B@1ab39d2; line: 53, column: 5] (through reference chain: org.cloudfoundry.client.v3.droplets.ListDropletsResponse$Json["resources"]->java.util.ArrayList[0])] with root cause

java.lang.NullPointerException: links value
	at java.util.Objects.requireNonNull(Objects.java:228) ~[na:1.8.0_144]
	at org.cloudfoundry.client.v3.droplets.DropletResource$Builder.putAllLinks(DropletResource.java:803) ~[cloudfoundry-client-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.cloudfoundry.client.v3.droplets.DropletResource.fromJson(DropletResource.java:391) ~[cloudfoundry-client-3.0.0.RELEASE.jar:3.0.0.RELEASE]
...
```

Thanks

**Comment by nebhale** [comment]
@zrob is a `null` value for a link reasonable?  I would have guessed that the link just shouldn’t exist, not that the value was `null`.

**Comment by Gerg** [comment]
@nebhale It looks like the package link can be null if the droplet was created by copying (and thus does not have a package). There are other cases on the API where links can be `null`: route mappings without processes and docker builds, for example.

**Comment by nebhale** [comment]
@Gerg So this is the preferred solution instead of just omitting the link itself?

**Comment by Gerg** [comment]
It looks like we sometimes also omit the field 😅 . Seems like from the java client's perspective, you have to be able to defend against null links.

I know the CLI prefers that the keys are always present with null values. I'll leave it to @zrob to decide which is the "correct" behavior.

**Comment by zrob** [comment]
null is the pattern we intended.  not sure of places that we omit

**Comment by nebhale** [comment]
Sounds good.
