### ISSUE TITLE
issue with ApplicationManifestUtils.read(path)

### ISSUE THREAD

**Issue by parasuramln** [cloudfoundry/cf-java-client#834]
error in reading yml file with service variable mappings.

![cf cli d](https://user-images.githubusercontent.com/22343548/32824637-b1ee46fe-ca07-11e7-9fdb-3ec0b0f9c96d.JPG)

if i use CLI it is able get buildpack mappping and Service instances name mappings.
but programatically by using **ApplicationManifestUtils.read(path)** throwing exception saying **buildpackName** not found .since it is unable to map with actual service variable.

**Comment by nebhale** [comment]
Can you please add a comment with a text version of the content above so that I can test it?

**Comment by parasuramln** [comment]
servicevariable:
  - &a9s-mongodb32 mongoDB
  - &a9s-postgresql94 postgreSQL
  - &a9s-rabbitmq36 rabbitMQ
  - &a9s-redis32 redis
  - &buildpackName java_buildpack
applications:
# component-1
- name: RepositoryService
  path: RepositoryService-0.0.1-SNAPSHOT.jar
  host: blr-RepositoryService-component
  instances: 1
  domain: apps.eu1-dev.mindsphere.io
  buildpack: *buildpackName
  env:
    oauth2_rest_connectionRequestTimeout: 180
    oauth2_rest_connectionTimeout: 180
    oauth2_rest_readTimeout: 180
  memory: 1GB
  services:
    - *a9s-mongodb32
    - *a9s-redis32  
# component-2
- name: DeployService
  path: DeployService-0.1.0-SNAPSHOT.jar
  host: blr-DeployService-component
  instances: 1
  domain: eu1-dev.mindsphere.io
  buildpack: *buildpackName
  env:
   oauth2_rest_connectionRequestTimeout: 180
   oauth2_rest_connectionTimeout: 180
   oauth2_rest_readTimeout: 180
  memory: 1GB
  services:
    - *a9s-postgresql94
    - *a9s-rabbitmq36

**Comment by parasuramln** [comment]
@nebhale 

i am facing issue while pushing code by using Application utils again with different issue.
java.lang.ClassCastException: Cannot cast java.lang.Integer to java.lang.String
	at java.lang.Class.cast(Unknown Source) ~[na:1.8.0_152]
	at org.cloudfoundry.operations.applications.ApplicationManifestUtils.lambda$null$3(ApplicationManifestUtils.java:157) ~[cloudfoundry-operations-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[na:1.8.0_152]
	at org.cloudfoundry.operations.applications.ApplicationManifestUtils.lambda$asMap$4(ApplicationManifestUtils.java:157) ~[cloudfoundry-operations-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at java.util.Optional.ifPresent(Unknown Source) ~[na:1.8.0_152]
	at org.cloudfoundry.operations.applications.ApplicationManifestUtils.as(ApplicationManifestUtils.java:131) ~[cloudfoundry-operations-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at org.cloudfoundry.operations.applications.ApplicationManifestUtils.asMap(ApplicationManifestUtils.java:156) ~[cloudfoundry-operations-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at org.cloudfoundry.operations.applications.ApplicationManifestUtils.asMapOfStringString(ApplicationManifestUtils.java:161) ~[cloudfoundry-operations-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at org.cloudfoundry.operations.applications.ApplicationManifestUtils.toApplicationManifest(ApplicationManifestUtils.java:312) ~[cloudfoundry-operations-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at org.cloudfoundry.operations.applications.ApplicationManifestUtils.lambda$doRead$8(ApplicationManifestUtils.java:223) ~[cloudfoundry-operations-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:1.8.0_152]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_152]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_152]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_152]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[na:1.8.0_152]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_152]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[na:1.8.0_152]
	at org.cloudfoundry.operations.applications.ApplicationManifestUtils.doRead(ApplicationManifestUtils.java:227) ~[cloudfoundry-operations-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at org.cloudfoundry.operations.applications.ApplicationManifestUtils.read(ApplicationManifestUtils.java:73) ~[cloudfoundry-operations-3.3.0.RELEASE.jar:3.3.0.RELEASE]

**Comment by twoseat** [comment]
@parasuramln Can you post the Manifest you're using when you get the error? And does it work if you push using the CLI?

(Also it's generally not a great idea to report an issue by adding it as a comment to a closed issue)

**Comment by parasuramln** [comment]
`applications:
# component-1
- name: testapp
  path: 12345.jar
  host: blr-RepositoryService-component
  instances: 1
  domain: apps.eu1-dev.mindsphere.io
  buildpack: java_buildpack
  env:
    oauth2_rest_connectionRequestTimeout: 180
    oauth2_rest_connectionTimeout: 180
    oauth2_rest_readTimeout: 180
  memory: 1GB
`
**through CLI its working fine.**

**Comment by twoseat** [comment]
Thanks for that. I'm going to open a new issue to track the solution - the issue is having integer values in `env`.

**Comment by parasuramln** [comment]
@nebhale 
CountDownLatch latch = new CountDownLatch(1);

` this.cloudFoundryOperations.applications()
    .pushManifest(PushApplicationManifestRequest.builder()
        .manifest(ApplicationManifest.builder()
            .from(ApplicationManifestUtils.read(Paths.get("D:/PROVIDER COCKPIT/DEPLOYING JARS/sample.yml")).get(0))
            .path(Paths.get("D:/PROVIDER COCKPIT/DEPLOYING JARS/SpringBootRestApp-0.0.1-SNAPSHOT.jar"))
            .build())
        .build())
    .doOnSubscribe(s -> this.logger.info("Deployment Started"))
    .doOnError(t -> this.logger.error("Deployment Failed", t))
    .doOnSuccess(v -> this.logger.info("Deployment Successful"))
    .subscribe(System.out::println, t -> latch.countDown(), latch::countDown);

latch.await(); `

**1. can you please tell me what is the purpose of Countdown latch in this case
2.how to replace System.out::println with log.info() in  .subscribe(System.out::println, t -> latch.countDown(), latch::countDown);**

**Comment by nebhale** [comment]
1.  Please take a look at [this video](https://www.youtube.com/watch?v=VN3SzWPsIuU) (specifically starting at 37:00) for more information about using a reactive API, and why the latch is important.
1.  `System.out::println` is a [Java method reference](https://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html).  If you expand that out into the lambda that it represents, you can replace it with either the call, or method reference you would like to use.

**Comment by parasuramln** [comment]
thank you so much @nebhale
