### ISSUE TITLE
NullPointerException token provider

### ISSUE THREAD

**Issue by andreaAlkalay** [cloudfoundry/cf-java-client#855]
Hi, 

Recently we are getting, from time to time the below exception:

```
java.lang.NullPointerException
at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.add(FluxReplay.java:749)
at reactor.core.publisher.ReplayProcessor.onNext(ReplayProcessor.java:434)
at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.lambda$null$2(AbstractUaaTokenProvider.java:203)
at java.util.Optional.ifPresent(Optional.java:159)
at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.lambda$extractRefreshToken$3(AbstractUaaTokenProvider.java:191)
at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:177)
at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
```

What could cause this?

Thanks a lot,
Andrea.

**Comment by twoseat** [comment]
Hi @andreaAlkalay - I'm working on reproducing this (hurray for intermittent failures!), but while I'm investigating can you tell me what version of the client you're using?

**Comment by twoseat** [comment]
@andreaAlkalay - we think this is an issue with the reactor core library, but it would be hugely helpful for us (and them) if you could tell me the exact version of cf java client you're using.
