### ISSUE TITLE
Support for Loggregator 2.x? 

### ISSUE THREAD

**Issue by adityajagtiani89** [cloudfoundry/cf-java-client#904]
Does this Java client include support for Loggregator 2.x? I'm interested in extracting metrics through the nozzle. 

Currently using a client based off of your jmx-consumer project and have seen customers run into a memory issue after a few days of running. 

```
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1845494055, max: 1860698112)
    at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
    at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
    at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
    at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
    at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
```
Any insight would be appreciated?

Thanks,
Aditya

**Comment by twoseat** [comment]
Hi @adityajagtiani89 - we don't currently support it, but I'll start work on it shortly. I've added it to the next release for now, but you shouldn't make any plans based on that as I don't know how easy it will be to add in.

**Comment by youngm** [comment]
Just so it is on your radar @twoseat here are 2 other enhancement requests in this area also:  https://github.com/cloudfoundry/cf-java-client/issues/851 and https://github.com/cloudfoundry/cf-java-client/issues/899

**Comment by youngm** [comment]
@twoseat @nebhale So, the loggregator team just announced the removal of support for the v1 firehose in 3 months.  How is the loggregator v2 support coming?

**Comment by twoseat** [comment]
I saw the announcement - that certainly sharpens the need! It got buried by some other priorities, but clearly it’s at the top of the list now.

**Comment by MasslessParticle** [comment]
@twoseat @nebhale 

Hello, I'm the anchor on the Loggregator team. 
I wanted to point out work we've done to make consumption of v2 easier (protobuf and certs not required!):

https://github.com/cloudfoundry/loggregator/blob/925b09a107d4d11286e0b84d5f2f090b30f6a397/docs/rlp_gateway.md

As work on this progresses, please reach out If you have any questions about how to consume the v2 api.

@jtuchscherer

**Comment by MasslessParticle** [comment]
@twoseat @nebhale the PR providing the `log_stream` url has been merged into CAPI master

https://github.com/cloudfoundry/cloud_controller_ng/pull/1301

**Comment by mudbbr** [comment]
is there any possibility of getting Loggregator v2 support anytime soon in this java-client?
