### ISSUE TITLE
What can cause ClosedChannelException during a GetInfoRequest?

### ISSUE THREAD

**Issue by chefhoobajoob** [cloudfoundry/cf-java-client#912]
I am using the cf-java-client during  startup of a cloud foundry app to discover other app instances, using Hazelcast's discovery SPI plumbing. The same code has been working without problems for months in multiple cloud foundry environments. I changed *something* about my application's startup or classpath that has resulted in a cryptic ClosedChannelException from the cf-java-client library. I'm certain it's something about my app, and not the cloud foundry environment itself, because if I try to launch an earlier build of my app in the same environment, it works without a problem. The code below has not changed since first use.

Here is the code that I'm using:

```java
// I've confirmed that HOST, USER, PASSWORD, ORG, SPACE are all non-null and valid for the env.
DefaultConnectionContext connection = DefaultConnectionContext.builder()
.skipSslValidation( true )
.secure( true )
.apiHost( getOrNull( _prefix, HOST ) )
.build();

PasswordGrantTokenProvider creds = PasswordGrantTokenProvider.builder()
.username( getOrNull( _prefix, USER ) )
.password( getOrNull( _prefix, PASSWORD ) )
.build();

//
// This block corresponds to the line below from the stack trace:
// com.hoobajoob.hazelcast.discovery.cloudfoundry.CloudFoundryDiscoveryStrategy.<init>(CloudFoundryDiscoveryStrategy.java:69)
//
ReactorCloudFoundryClient cfClient = ReactorCloudFoundryClient.builder()
.connectionContext( connection )
.tokenProvider( creds )
.build(); // this is line 69

ReactorDopplerClient dopplerClient = ReactorDopplerClient.builder()
.connectionContext( connection )
.tokenProvider( creds )
.build();

ReactorUaaClient uaaClient = ReactorUaaClient.builder()
.connectionContext( connection )
.tokenProvider( creds )
.build();

ReactorNetworkingClient netClient = ReactorNetworkingClient.builder()
.connectionContext( connection )
.tokenProvider( creds )
.build();

_ops = DefaultCloudFoundryOperations.builder()
.organization( getOrNull( _prefix, ORG ) )
.space( getOrNull( _prefix, SPACE ) )
.cloudFoundryClient( cfClient )
.dopplerClient( dopplerClient )
.uaaClient( uaaClient )
.networkingClient( netClient )
.build();


//
// This block corresponds to the line below from the stack trace:
// com.hoobajoob.hazelcast.discovery.cloudfoundry.CloudFoundryDiscoveryStrategy.<init>(CloudFoundryDiscoveryStrategy.java:98)
//
GetInfoResponse response = ( (DefaultCloudFoundryOperations) _ops ).getCloudFoundryClient()
.info()
.get( GetInfoRequest.builder().build() )
.block();  // this is line 98
```

...and here is the stack trace:
```
 java.lang.RuntimeException: Failed to configure discovery strategies
  at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryProviders(DefaultDiscoveryService.java:155)
  at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:60)
  at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
  at com.hazelcast.instance.Node.createDiscoveryService(Node.java:217)
  at com.hazelcast.instance.Node.<init>(Node.java:185)
  at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
  at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
  at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
  at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
  at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
  at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$join$0(HazelcastClusterManager.java:161)
  at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
  at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
 Caused by: reactor.core.Exceptions$ReactiveException: java.nio.channels.ClosedChannelException
  at reactor.core.Exceptions.propagate(Exceptions.java:326)
  at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
  at reactor.core.publisher.Mono.block(Mono.java:1175)
>>>at com.hoobajoob.hazelcast.discovery.cloudfoundry.CloudFoundryDiscoveryStrategy.<init>(CloudFoundryDiscoveryStrategy.java:98)
  at com.hoobajoob.hazelcast.discovery.cloudfoundry.CloudFoundryDiscoveryStrategyFactory.newDiscoveryStrategy(CloudFoundryDiscoveryStrategyFactory.java:27)
  at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryProvider(DefaultDiscoveryService.java:204)
  at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryProviders(DefaultDiscoveryService.java:145)
  ... 15 more
  Suppressed: java.lang.Exception: #block terminated with an error
          at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
          ... 20 more
 Caused by: java.nio.channels.ClosedChannelException
  at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(...)(Unknown Source)
  Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
 Assembly trace from producer [reactor.core.publisher.MonoMap] :
  reactor.core.publisher.Mono.checkpoint(Mono.java:1367)
  reactor.core.publisher.Mono.checkpoint(Mono.java:1317)
  org.cloudfoundry.reactor._RootPayloadRootProvider.getPayload(_RootPayloadRootProvider.java:71)
  org.cloudfoundry.reactor._RootPayloadRootProvider.doGetRoot(_RootPayloadRootProvider.java:45)
  org.cloudfoundry.reactor._DelegatingRootProvider.doGetRoot(_DelegatingRootProvider.java:39)
  org.cloudfoundry.reactor.AbstractRootProvider.getRoot(AbstractRootProvider.java:66)
  org.cloudfoundry.reactor.client._ReactorCloudFoundryClient.getRootV2(_ReactorCloudFoundryClient.java:389)
  org.cloudfoundry.reactor.client.ReactorCloudFoundryClient.access$4801(ReactorCloudFoundryClient.java:60)
  org.cloudfoundry.reactor.client.ReactorCloudFoundryClient$InitShim.getRootV2(ReactorCloudFoundryClient.java:739)
  org.cloudfoundry.reactor.client.ReactorCloudFoundryClient.getRootV2(ReactorCloudFoundryClient.java:1307)
  org.cloudfoundry.reactor.client._ReactorCloudFoundryClient.applicationUsageEvents(_ReactorCloudFoundryClient.java:122)
  org.cloudfoundry.reactor.client.ReactorCloudFoundryClient.access$501(ReactorCloudFoundryClient.java:60)
  org.cloudfoundry.reactor.client.ReactorCloudFoundryClient$InitShim.applicationUsageEvents(ReactorCloudFoundryClient.java:180)
  org.cloudfoundry.reactor.client.ReactorCloudFoundryClient.<init>(ReactorCloudFoundryClient.java:119)
  org.cloudfoundry.reactor.client.ReactorCloudFoundryClient.<init>(ReactorCloudFoundryClient.java:60)
  org.cloudfoundry.reactor.client.ReactorCloudFoundryClient$Builder.build(ReactorCloudFoundryClient.java:1611)
  com.hoobajoob.hazelcast.discovery.cloudfoundry.CloudFoundryDiscoveryStrategy.<init>(CloudFoundryDiscoveryStrategy.java:69)
  com.hoobajoob.hazelcast.discovery.cloudfoundry.CloudFoundryDiscoveryStrategyFactory.newDiscoveryStrategy(CloudFoundryDiscoveryStrategyFactory.java:27)
  com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryProvider(DefaultDiscoveryService.java:204)
  com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryProviders(DefaultDiscoveryService.java:145)
  com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:60)
  com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
  com.hazelcast.instance.Node.createDiscoveryService(Node.java:217)
  com.hazelcast.instance.Node.<init>(Node.java:185)
  com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
  com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
  com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
  com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
  com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
  io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$join$0(HazelcastClusterManager.java:161)
  io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
  io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
 Error has been observed by the following operator(s):
  |_      Mono.checkpoint(_RootPayloadRootProvider.java:71)
  |_      Mono.checkpoint(ReactorInfo.java:47)
 
  Suppressed:     reactor.core.publisher.Mono.checkpoint(Mono.java:1367)
  reactor.core.publisher.Mono.checkpoint(Mono.java:1317)
  org.cloudfoundry.reactor.client.v2.info.ReactorInfo.get(ReactorInfo.java:47)
  com.hoobajoob.hazelcast.discovery.cloudfoundry.CloudFoundryDiscoveryStrategy.<init>(CloudFoundryDiscoveryStrategy.java:97)
  com.hoobajoob.hazelcast.discovery.cloudfoundry.CloudFoundryDiscoveryStrategyFactory.newDiscoveryStrategy(CloudFoundryDiscoveryStrategyFactory.java:27)
  com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryProvider(DefaultDiscoveryService.java:204)
  com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryProviders(DefaultDiscoveryService.java:145)
  com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:60)
  com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
  com.hazelcast.instance.Node.createDiscoveryService(Node.java:217)
  com.hazelcast.instance.Node.<init>(Node.java:185)
```

Any suggestions? It seems to be pointing at the credentials, but the configured values here haven't changed, and the same settings are used with the older build, which doesn't generate this exception. What could I be missing?

**Comment by chefhoobajoob** [comment]
Found it. It was a classpath problem, caused by an additional jar file that had a conflicting netty version:

https://github.com/vert-x3/vertx-mysql-postgresql-client/issues/115
