### ISSUE TITLE
Proxy closes connection, then no further operation possible

### ISSUE THREAD

**Issue by eaglerainbow** [cloudfoundry/cf-java-client#930]
This is in reference to https://github.com/promregator/promregator/issues/83, where we have the following situation:
* Connection to the api.cf server has to be be made using a corporate proxy (direct connection is prohibited technically on network level).
* The application sends requests to the Cloud Controller regularly (e.g. every minute or so).
* Apparently cf-java-client (more precise: netty beneath it) seems to pool the proxy connections. It keeps the TCP connections open as much as possible (observed that using network tracing tools).
* The proxy apparently has a timeout configured for its connections. As the pooled proxy connections eventually time out, those connections get closed.
* The SslEngine on top of the proxy connection then detects this and considers itself to be closed. However, netty/cf-java-client keeps trying to send requests via the closed connection. Thus, they fail on each next request sent.

(at least this is what I make out of the log information provided there). 

Apparently the two most interesting log statements are:
``` 
2018-12-12 01:18:43.147  WARN 9 --- [ry-client-nio-2] i.n.c.AbstractChannelHandlerContext      : An exception '{}' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:

io.netty.handler.proxy.ProxyConnectException: http, none, /xxx.yyy.zzz.aaa:8080 => api.cf.example.com:443, disconnected
        at io.netty.handler.proxy.ProxyHandler.channelInactive(ProxyHandler.java:236) [netty-handler-proxy-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420) [netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
``` 

and 
```
2018-12-12 01:26:56.059 ERROR 9 --- [ry-client-nio-4] o.c.p.cfaccessor.ReactiveCFAccessorImpl  : Async retrieval of retrieveSpaceSummary with key <other-uuid> raised a reactor error

javax.net.ssl.SSLException: SSLEngine closed already
        at io.netty.handler.ssl.SslHandler.wrap(...)(Unknown Source) ~[netty-handler-4.1.29.Final.jar!/:4.1.29.Final]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly trace from producer [reactor.core.publisher.MonoPeek] :
        reactor.core.publisher.Mono.checkpoint(Mono.java:1375)
        reactor.core.publisher.Mono.checkpoint(Mono.java:1325)
        org.cloudfoundry.reactor.client.v2.spaces.ReactorSpaces.getSummary(ReactorSpaces.java:162)
        org.cloudfoundry.promregator.cfaccessor.ReactiveCFAccessorImpl.lambda$retrieveSpaceSummary$8(ReactiveCFAccessorImpl.java:276)
``` 
whereas the second exception can be found in various variants (depending on what command was triggered).

Do you agree to my analysis mentioned above?
Do you have any idea how proxy connection pool management of cf-java-client/netty can be influenced in any way? Is there an option for a "maximal connection pool timeout" (e.g. the maximal lifetime of a connection in the pool)? Is there a way to signal a disposal of all connections which then would trigger attempts to reconnect from scratch?
Any other alternative ideas how to tackle the situation?

Thanks for your thoughts!

**Comment by eaglerainbow** [comment]
Created https://github.com/netty/netty/issues/8685 for clarification.

**Comment by mheath** [comment]
I'm seeing this issue too. I'm happy to help find a solution.

**Comment by dmikusa-pivotal** [comment]
My only thought from the cf-java-client side is that you might be able to [customize the DefaultConnectionContext](https://github.com/cloudfoundry/cf-java-client/blob/190f26a296789b2b7928877b318c33981dbe8707/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/_DefaultConnectionContext.java). It's hard to say though as I don't have an environment with proxies to attempt to recreate that. This is where I'd look though as the Netty HTTP Client is what's managing the pools and would ultimately be responsible for detecting if a connection were closed and evicting it (unless it's not been closed out properly, we did fix an issue recently in the 4.x and 5.x branches that corrected a condition where connections were not being closed correctly).

At any rate, this is an old issue and I'm not sure if it still applies. If you're still seeing this with the latest 4.x or 5.x  please open a new issue and provide some up-to-date details on what you're experiencing. Thanks!
