### ISSUE TITLE
java.lang.IllegalStateException: failed to create a child event loop (facing sporadic issue)

### ISSUE THREAD

**Issue by parasuramln** [cloudfoundry/cf-java-client#943]
`ava.lang.IllegalStateException: failed to create a child event loop
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88) ~[netty-common-4.1.25.Final.jar:4.1.25.Final]
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[netty-common-4.1.25.Final.jar:4.1.25.Final]
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[netty-common-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
at reactor.ipc.netty.resources.DefaultLoopResources.<init>(DefaultLoopResources.java:70) ~[reactor-netty-0.7.8.RELEASE.jar:0.7.8.RELEASE]
at reactor.ipc.netty.resources.DefaultLoopResources.<init>(DefaultLoopResources.java:57) ~[reactor-netty-0.7.8.RELEASE.jar:0.7.8.RELEASE]
at reactor.ipc.netty.resources.LoopResources.create(LoopResources.java:83) ~[reactor-netty-0.7.8.RELEASE.jar:0.7.8.RELEASE]
at org.cloudfoundry.reactor._DefaultConnectionContext.getThreadPool(_DefaultConnectionContext.java:233) ~[cloudfoundry-client-reactor-3.12.0.RELEASE.jar:na]
at org.cloudfoundry.reactor.DefaultConnectionContext.access$2601(DefaultConnectionContext.java:25) ~[cloudfoundry-client-reactor-3.12.0.RELEASE.jar:na]
at org.cloudfoundry.reactor.DefaultConnectionContext$InitShim.getThreadPool(DefaultConnectionContext.java:215) ~[cloudfoundry-client-reactor-3.12.0.RELEASE.jar:na]
at org.cloudfoundry.reactor.DefaultConnectionContext.getThreadPool(DefaultConnectionContext.java:415) ~[cloudfoundry-client-reactor-3.12.0.RELEASE.jar:na]
at org.cloudfoundry.reactor._DefaultConnectionContext.lambda$getHttpClient$5(_DefaultConnectionContext.java:104) ~[cloudfoundry-client-reactor-3.12.0.RELEASE.jar:na]
at reactor.ipc.netty.http.client.HttpClient.<init>(HttpClient.java:135) ~[reactor-netty-0.7.8.RELEASE.jar:0.7.8.RELEASE]
at reactor.ipc.netty.http.client.HttpClient.<init>(HttpClient.java:63) ~[reactor-netty-0.7.8.RELEASE.jar:0.7.8.RELEASE]
at reactor.ipc.netty.http.client.HttpClient$Builder.build(HttpClient.java:461) ~[reactor-netty-0.7.8.RELEASE.jar:0.7.8.RELEASE]
at reactor.ipc.netty.http.client.HttpClient.create(HttpClient.java:86) ~[reactor-netty-0.7.8.RELEASE.jar:0.7.8.RELEASE]
at org.cloudfoundry.reactor._DefaultConnectionContext.getHttpClient(_DefaultConnectionContext.java:101) ~[cloudfoundry-client-reactor-3.12.0.RELEASE.jar:na]
at org.cloudfoundry.reactor.DefaultConnectionContext.access$2001(DefaultConnectionContext.java:25) ~[cloudfoundry-client-reactor-3.12.0.RELEASE.jar:na]
at org.cloudfoundry.reactor.DefaultConnectionContext$InitShim.getHttpClient(DefaultConnectionContext.java:117) ~[cloudfoundry-client-reactor-3.12.0.RELEASE.jar:na]
at org.cloudfoundry.reactor.DefaultConnectionContext.<init>(DefaultConnectionContext.java:76) ~[cloudfoundry-client-reactor-3.12.0.RELEASE.jar:na]
at org.cloudfoundry.reactor.DefaultConnectionContext.<init>(DefaultConnectionContext.java:25) ~[cloudfoundry-client-reactor-3.12.0.RELEASE.jar:na]
at org.cloudfoundry.reactor.DefaultConnectionContext$Builder.build(DefaultConnectionContext.java:1041) ~[cloudfoundry-client-reactor-3.12.0.RELEASE.jar:na]`

**Comment by violetagg** [comment]
@parasuramln Is this the whole stack trace? What is the OS?

**Comment by parasuramln** [comment]
`Caused by: io.netty.channel.ChannelException: failed to open a new selector
at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:177) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:151) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[netty-common-4.1.25.Final.jar:4.1.25.Final]
... 35 common frames omitted
Caused by: java.io.IOException: No file descriptors available
at sun.nio.ch.EPollArrayWrapper.epollCreate(Native Method) ~[na:1.8.0_171]
at sun.nio.ch.EPollArrayWrapper.<init>(EPollArrayWrapper.java:130) ~[na:1.8.0_171]
at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:69) ~[na:1.8.0_171]
at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36) ~[na:1.8.0_171]
at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
... 39 common frames omitted`

**Comment by parasuramln** [comment]
OS is : LINUX

**Comment by violetagg** [comment]
@parasuramln Can you tell us `ulimit` and then `lsof | wc -l`?

**Comment by nebhale** [comment]
@parasuramln We believe that the problem is resource exhaustion but can only tell for sure with output from those two commands (`ulimit` and `lsof | wc -l`).  You’ll need to get shell access to the container where your application is having trouble, at the time your application is having trouble, and execute those commands.  The “Ulimits - not configured” output isn’t accurate because Linux _always_ has a ulimit configured even if it just the default.

**Comment by parasuramln** [comment]
after increasing ulimit we didn't faced this issue as of now . thank you for quick response.
