### ISSUE TITLE
Push manifest fails with Unknown Cloud Foundry Exception

### ISSUE THREAD

**Issue by cah-steveanderson** [cloudfoundry/cf-java-client#997]
We have our own CF application deployer that uses the Java client libraries to push to Cloud Foundry using an application manifest. This pattern has worked well until we tried pushing a new application using this method.

With this new application, when executing org.cloudfoundry.operations.applications.pushManifest, an exception is thrown (stack trace below). We can successfully deploy this application using the manifest with the pcf CLI.

```
org.cloudfoundry.UnknownCloudFoundryException: Unknown Cloud Foundry Exception
	at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$null$9(ErrorPayloadMapper.java:100)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:115)
	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:345)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:104)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:469)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1069)
	at reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.onComplete(MonoReduceSeed.java:150)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:130)
	at reactor.ipc.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:377)
	at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:202)
	at reactor.ipc.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:342)
	at reactor.ipc.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:336)
	at reactor.ipc.netty.channel.ChannelOperations.onHandlerTerminate(ChannelOperations.java:420)
	at reactor.ipc.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:597)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:134)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:282)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1010)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1409)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:927)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoPeek] :
	reactor.core.publisher.Mono.checkpoint(Mono.java:1367)
	reactor.core.publisher.Mono.checkpoint(Mono.java:1317)
	org.cloudfoundry.reactor.client.v2.applications.ReactorApplicationsV2.upload(ReactorApplicationsV2.java:233)
	org.cloudfoundry.operations.applications.DefaultApplications.requestUploadApplication(DefaultApplications.java:1639)
	org.cloudfoundry.operations.applications.DefaultApplications.lambda$null$153(DefaultApplications.java:1864)
	reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onNext(MonoSubscribeOn.java:143)
	reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1626)
	reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.trySchedule(MonoSubscribeOn.java:186)
	reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onSubscribe(MonoSubscribeOn.java:131)
	reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	reactor.core.publisher.Mono.subscribe(Mono.java:3080)
	reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:123)
	reactor.core.scheduler.WorkerTask.call(WorkerTask.java:69)
	reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
Error has been observed by the following operator(s):
	|_	Mono.checkpoint(ReactorApplicationsV2.java:233)
	|_	Mono.checkpoint(DefaultApplications.java:421)
	Suppressed: 	reactor.core.publisher.Mono.checkpoint(Mono.java:1367)
	reactor.core.publisher.Mono.checkpoint(Mono.java:1317)
	org.cloudfoundry.operations.applications.DefaultApplications.pushManifest(DefaultApplications.java:421)
	REDACTED
		at reactor.core.publisher.MonoOnAssembly.<init>(MonoOnAssembly.java:62)
		at reactor.core.publisher.Mono.checkpoint(Mono.java:1367)
		at reactor.core.publisher.Mono.checkpoint(Mono.java:1317)
		at org.cloudfoundry.operations.applications.DefaultApplications.pushManifest(DefaultApplications.java:421)
		REDACTED
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:223)
		at org.springframework.shell.Shell.evaluate(Shell.java:169)
		at org.springframework.shell.Shell.run(Shell.java:134)
		at org.springframework.shell.jline.InteractiveShellApplicationRunner.run(InteractiveShellApplicationRunner.java:84)
		at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:781)
		at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:771)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
		REDACTED
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:126)
		at reactor.core.publisher.Mono.block(Mono.java:1199)
		REDACTED
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:223)
		at org.springframework.shell.Shell.evaluate(Shell.java:169)
		at org.springframework.shell.Shell.run(Shell.java:134)
		at org.springframework.shell.jline.InteractiveShellApplicationRunner.run(InteractiveShellApplicationRunner.java:84)
		at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:781)
		at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:771)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
		REDACTED
```

I enabled debug logging on reactor and was able to capture this right before the end:
```
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 48 54 54 50 2f 31 2e 30 20 35 30 32 20 42 61 64 |HTTP/1.0 502 Bad|
|00000010| 20 47 61 74 65 77 61 79 0d 0a 43 61 63 68 65 2d | Gateway..Cache-|
|00000020| 43 6f 6e 74 72 6f 6c 3a 20 6e 6f 2d 63 61 63 68 |Control: no-cach|
|00000030| 65 0d 0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a 20 63 |e..Connection: c|
|00000040| 6c 6f 73 65 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 |lose..Content-Ty|
|00000050| 70 65 3a 20 74 65 78 74 2f 68 74 6d 6c 0d 0a 0d |pe: text/html...|
|00000060| 0a 3c 68 74 6d 6c 3e 3c 62 6f 64 79 3e 3c 68 31 |.<html><body><h1|
|00000070| 3e 35 30 32 20 42 61 64 20 47 61 74 65 77 61 79 |>502 Bad Gateway|
|00000080| 3c 2f 68 31 3e 0a 54 68 65 20 73 65 72 76 65 72 |</h1>.The server|
|00000090| 20 72 65 74 75 72 6e 65 64 20 61 6e 20 69 6e 76 | returned an inv|
|000000a0| 61 6c 69 64 20 6f 72 20 69 6e 63 6f 6d 70 6c 65 |alid or incomple|
|000000b0| 74 65 20 72 65 73 70 6f 6e 73 65 2e 0a 3c 2f 62 |te response..</b|
|000000c0| 6f 64 79 3e 3c 2f 68 74 6d 6c 3e 0a             |ody></html>.    |
+--------+-------------------------------------------------+----------------+
```

**Comment by nictas** [comment]
`502 Bad Gateway`s are usually returned when one server has problems when communicating with another - for example, you request the creation of a service instance, the CF controller makes a call to the appropriate service broker, the broker returns `400 Bad Request` and the CF controller returns this error back to you as `502 Bad Gateway`.

Is there any proxy between you and the CF controller? It doesn't look like this error came from the CF controller itself - it's XML and therefore does not follow the controller's API.

**Comment by parasuramln** [comment]
@cah-steveanderson  how did you enable  debug logging level in reactor , can you help me to enable in my spring boot project..

**Comment by cah-steveanderson** [comment]
> @cah-steveanderson how did you enable debug logging level in reactor , can you help me to enable in my spring boot project..

Working off of memory here, on the specific properties, but essentially just update the application.properties with the following values:

`reactor.ipc.netty.channel.ContextHandler=DEBUG
reactor.ipc.netty.http.server.HttpServer=DEBUG`

**Comment by dmikusa-pivotal** [comment]
This doesn't appear to be a client-related issue as the 502 is a server-side problem. Closing.
